FROM debian:bookworm-20251208-slim
ARG NVIM_VERSION=v0.11.7

# install latest nvim
RUN apt-get update && \
    apt-get install -y curl jq uuid-runtime git tree && \
    useradd -ms /bin/bash user

RUN curl -LO "https://github.com/neovim/neovim/releases/download/${NVIM_VERSION}/nvim-linux-x86_64.tar.gz" && \
    tar xzf nvim-linux-x86_64.tar.gz --strip-components=1 -C /usr/local && \
    rm nvim-linux-x86_64.tar.gz

# convenience
RUN mkdir -p /home/user/.config/nvim/lua
RUN mkdir -p /home/user/.config/nvim/fnl

# Make sure you build with hotpot's root dir as the build context!
COPY ./ /home/user/hotpot

RUN chown -R user:user /home/user
USER user
WORKDIR /home/user/hotpot

ENTRYPOINT ["/bin/bash"]
CMD ["test/test.sh"]
