FROM debian:bullseye-20211220-slim

# install latest nvim
RUN apt-get update && \
    apt-get install -y curl jq uuid-runtime git && \
    curl -sL https://api.github.com/repos/neovim/neovim/releases/latest | \
    jq -r '.assets[].browser_download_url' | \
    grep nvim-linux64.tar.gz | \
    head -n 1 | \
    xargs curl -LO && \
    tar zxf nvim-linux64.tar.gz && \
    useradd -ms /bin/bash user

RUN ln -s /nvim-linux64/bin/nvim /bin/nvim

# convenience
RUN mkdir -p /home/user/.config/nvim/lua
RUN mkdir -p /home/user/.config/nvim/fnl

# Make sure you build with hotpot's root dir as the build context!
COPY ./ /home/user/hotpot

RUN chown -R user:user /home/user
USER user
WORKDIR /home/user/hotpot

ENTRYPOINT ["/bin/bash"]
CMD ["test/test.sh"]
