-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local fnl_path = create_file(path("config", "fnl/abc.fnl"), "{:works true}")
local lua_path = path("cache", "/lua/abc.lua")
local nvim = start_nvim()
nvim:lua("require'hotpot'")
do
  local case_2_ = string.find(read_file(lua_path)[1], "-- @generated by hotpot")
  if (case_2_ == 1) then
    OK(string.format(("inserts ownership header" or "")))
  else
    local __1_auto = case_2_
    FAIL(string.format(("inserts ownership header" or "")))
  end
end
nvim:close()
return exit()