(import-macros {: setup : expect} :test.macros)
(setup)

(local fnl-path (create-file (path :config :fnl/abc.fnl)
                             "{:works true}"))
(local lua-path (path :cache :/lua/abc.lua))

(local nvim (start-nvim))
(nvim:lua "require'hotpot'")
(expect 1 (string.find (. (read-file lua-path) 1) "-- @generated by hotpot")
        "inserts ownership header")

(nvim:close)
(exit)
