-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local fnl_path = create_file(path("config", "code.fnl"), "(+ 1 1)")
local lua_path = path("cache", "code.lua")
local nvim = start_nvim()
nvim:lua("require'hotpot'")
do
  local case_2_ = read_file(lua_path)
  if ((_G.type(case_2_) == "table") and true and (case_2_[2] == "return (1 + 1)")) then
    local _ = case_2_[1]
    OK(string.format(("creates lua file" or "")))
  else
    local __1_auto = case_2_
    FAIL(string.format(("creates lua file" or "")))
  end
end
create_file(fnl_path, "(+ 1 2)")
nvim:cmd("e %s", fnl_path)
nvim:cmd("w")
do
  local case_4_ = read_file(lua_path)
  if ((_G.type(case_4_) == "table") and true and (case_4_[2] == "return (1 + 2)")) then
    local _ = case_4_[1]
    OK(string.format(("updates lua file on save" or "")))
  else
    local __1_auto = case_4_
    FAIL(string.format(("updates lua file on save" or "")))
  end
end
nvim:cmd("Hotpot watch disable")
create_file(fnl_path, "(+ 1 3)")
nvim:cmd("e %s", fnl_path)
nvim:cmd("w")
do
  local case_6_ = read_file(lua_path)
  if ((_G.type(case_6_) == "table") and true and (case_6_[2] == "return (1 + 2)")) then
    local _ = case_6_[1]
    OK(string.format(("does not update lua file on save after disable" or "")))
  else
    local __1_auto = case_6_
    FAIL(string.format(("does not update lua file on save after disable" or "")))
  end
end
nvim:cmd("Hotpot watch enable")
nvim:cmd("e %s", fnl_path)
nvim:cmd("w")
do
  local case_8_ = read_file(lua_path)
  if ((_G.type(case_8_) == "table") and true and (case_8_[2] == "return (1 + 3)")) then
    local _ = case_8_[1]
    OK(string.format(("does update lua file on save after enable" or "")))
  else
    local __1_auto = case_8_
    FAIL(string.format(("does update lua file on save after enable" or "")))
  end
end
nvim:close()
return exit()