-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local config_path = create_file(path("config", ".hotpot.fnl"), "{:schema :hotpot/2\n                                  :target :cache\n                                  :ignore [:fnl/ignore.fnlm]}")
local module_file = create_file(path("config", "fnl/my/mod.fnl"), "(print :loaded-my-mod)")
local ft_plugin = create_file(path("config", "ftplugin/fyle.fnl"), "(print :loaded-ft-plugin-fyle)")
local nvim = start_nvim()
nvim:lua("require'hotpot'")
local output = nvim:cmd("set ft=fyle")
if (output == "loaded-ft-plugin-fyle") then
  OK(string.format(("automatically loads ftplugin for ft on first boot" or "")))
else
  local __1_auto = output
  FAIL(string.format(("automatically loads ftplugin for ft on first boot" or "")))
end
local output0 = nvim:lua("require'my.mod'")
if (output0 == "loaded-my-mod") then
  OK(string.format(("can require my.mod" or "")))
else
  local __1_auto = output0
  FAIL(string.format(("can require my.mod" or "")))
end
nvim:close()
return exit()