-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local fnl_path = create_file(path("config", "code.fnl"), "(+ 1 1)")
local nvim = start_nvim()
nvim:lua("require'hotpot'")
local output = nvim:cmd("Fnlfile= %s", fnl_path)
if (output == "2") then
  OK(string.format((":Fnlfile= <path> evaluates file and prints result" or "")))
else
  local __1_auto = output
  FAIL(string.format((":Fnlfile= <path> evaluates file and prints result" or "")))
end
local output0 = nvim:cmd("Fnlfile %s", fnl_path)
if (output0 == "") then
  OK(string.format((":Fnlfile <path> evaluates file and prints nothing" or "")))
else
  local __1_auto = output0
  FAIL(string.format((":Fnlfile <path> evaluates file and prints nothing" or "")))
end
local output1 = nvim:cmd("Fnlfile- %s", fnl_path)
if (output1 == "return (1 + 1)") then
  OK(string.format((":Fnlfile- <path> compiles file and prints result" or "")))
else
  local __1_auto = output1
  FAIL(string.format((":Fnlfile- <path> compiles file and prints result" or "")))
end
nvim:close()
return exit()