-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local fnl_path = create_file(path("config", "fnl/user/init.fnl"), "{:works true}")
local lua_path = path("cache", "lua/user/init.lua")
local config_lua_path = create_file(path("config", "lua/user/something.lua"), "print'hi'")
local cache_lua_path = create_file(path("cache", "lua/mod.lua"), "print'hi'")
local nvim = start_nvim()
nvim:lua("_G.called = false\n          vim.ui.select = function(choices, options, callback)\n  _G.called = true\n  callback('yes', 1)\nend")
nvim:lua("require'hotpot'")
nvim:cmd("edit %s", fnl_path)
nvim:cmd("write")
do
  local case_2_ = vim.uv.fs_stat(lua_path)
  if (_G.type(case_2_) == "table") then
    OK(string.format(("did create cache lua file" or "")))
  else
    local __1_auto = case_2_
    FAIL(string.format(("did create cache lua file" or "")))
  end
end
do
  local case_4_ = vim.uv.fs_stat(config_lua_path)
  if (_G.type(case_4_) == "table") then
    OK(string.format(("did not remove config lua file" or "")))
  else
    local __1_auto = case_4_
    FAIL(string.format(("did not remove config lua file" or "")))
  end
end
do
  local case_6_ = vim.uv.fs_stat(cache_lua_path)
  if (case_6_ == nil) then
    OK(string.format(("did remove cache lua file" or "")))
  else
    local __1_auto = case_6_
    FAIL(string.format(("did remove cache lua file" or "")))
  end
end
local output = nvim:lua("print(_G.called)")
if (output == "false") then
  OK(string.format(("did not show any confirm prompt" or "")))
else
  local __1_auto = output
  FAIL(string.format(("did not show any confirm prompt" or "")))
end
nvim:close()
return exit()