-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
package.preload["test.utils"] = package.preload["test.utils"] or function(...)
  local function read_file(path)
    return table.concat(vim.fn.readfile(path), "\\n")
  end
  local function write_file(path, lines)
    vim.fn.mkdir(vim.fs.dirname(path), "p")
    local fh = assert(io.open(path, "w"), ("fs.write-file! io.open failed:" .. path))
    local function close_handlers_13_(ok_14_, ...)
      fh:close()
      if ok_14_ then
        return ...
      else
        return error(..., 0)
      end
    end
    local function _2_()
      return fh:write(lines)
    end
    local _4_
    do
      local t_3_ = _G
      if (nil ~= t_3_) then
        t_3_ = t_3_.package
      else
      end
      if (nil ~= t_3_) then
        t_3_ = t_3_.loaded
      else
      end
      if (nil ~= t_3_) then
        t_3_ = t_3_.fennel
      else
      end
      _4_ = t_3_
    end
    local or_8_ = _4_ or _G.debug
    if not or_8_ then
      local function _9_()
        return ""
      end
      or_8_ = {traceback = _9_}
    end
    return close_handlers_13_(_G.xpcall(_2_, or_8_.traceback))
  end
  local results = {passes = 0, fails = 0}
  local function OK(message)
    results.passes = (1 + results.passes)
    return print("OK", message)
  end
  local function FAIL(message)
    results.fails = (1 + results.fails)
    return print("FAIL", message)
  end
  local function exit()
    print("\n")
    return os.exit(results.fails)
  end
  local function start_nvim()
    local channel = vim.fn.jobstart({(vim.env.NVIM_BIN or "nvim"), "--embed", "--headless"}, {rpc = true})
    local nvim
    local function _10_(this)
      return vim.fn.jobstop(channel)
    end
    local function _11_(this, cmd, ...)
      local case_12_ = vim.rpcrequest(channel, "nvim_exec2", string.format(cmd, ...), {output = true})
      if ((_G.type(case_12_) == "table") and (nil ~= case_12_.output)) then
        local output = case_12_.output
        return output
      else
        local _ = case_12_
        return nil
      end
    end
    local function _14_(this, src)
      local case_15_ = vim.rpcrequest(channel, "nvim_exec2", table.concat({"lua << EOF", src, "EOF"}, "\n"), {output = true})
      if ((_G.type(case_15_) == "table") and (nil ~= case_15_.output)) then
        local output = case_15_.output
        return output
      else
        local _ = case_15_
        return nil
      end
    end
    nvim = {channel = channel, close = _10_, cmd = _11_, lua = _14_}
    nvim:lua("vim.opt.runtimepath:prepend(vim.uv.cwd())")
    nvim:lua("vim.secure.read = function(path) return table.concat(vim.fn.readfile(path), '\\n') end")
    return nvim
  end
  local function create_file(path, content)
    write_file(path, content)
    return path
  end
  local function path(_in, ...)
    if (_in == "cache") then
      return vim.fs.joinpath(vim.fn.stdpath("data"), "site", "pack", "hotpot", "opt", "hotpot-config-cache", ...)
    else
      local _ = _in
      return vim.fs.joinpath(vim.fn.stdpath(_in), ...)
    end
  end
  return {["write-file"] = write_file, ["read-file"] = read_file, ["create-file"] = create_file, path = path, OK = OK, FAIL = FAIL, exit = exit, ["start-nvim"] = start_nvim, NVIM_APPNAME = vim.env.NVIM_APPNAME}
end
local _local_18_ = require("test.utils")
local FAIL = _local_18_.FAIL
local NVIM_APPNAME = _local_18_.NVIM_APPNAME
local OK = _local_18_.OK
local create_file = _local_18_["create-file"]
local exit = _local_18_.exit
local path = _local_18_.path
local read_file = _local_18_["read-file"]
local start_nvim = _local_18_["start-nvim"]
local write_file = _local_18_["write-file"]
local config_path = create_file(path("config", ".hotpot.fnl"), "{:schema :hotpot/2\n                                  :target :colocate\n                                  :ignore [:fnl/ignore.fnlm]}")
local abc_fnl_path = create_file(path("config", "fnl/abc.fnl"), "{:works true}")
local abc_lua_path = path("config", "lua/abc.lua")
local xyz_fnl_path = create_file(path("config", "fnl/xyz.fnl"), "{:works true}")
local xyz_lua_path = path("config", "lua/xyz.lua")
local fnlm_path = create_file(path("config", "fnl/macro.fnlm"), "{}")
local ignore_fnlm_path = create_file(path("config", "fnl/ignore.fnlm"), "{}")
local function a_newer_than_b_3f(mtime1, mtime2)
  local s1 = mtime1.sec
  local n1 = mtime1.nsec
  local s2 = mtime2.sec
  local n2 = mtime2.nsec
  return (((s2 == s1) and (n2 < n1)) or (s2 < s1))
end
local function a_equal_b_3f(mtime1, mtime2)
  local s1 = mtime1.sec
  local n1 = mtime1.nsec
  local s2 = mtime2.sec
  local n2 = mtime2.nsec
  return ((s1 == s2) and (n1 == n2))
end
local nvim = start_nvim()
nvim:lua("require'hotpot'")
do
  local case_19_ = vim.uv.fs_stat(abc_lua_path)
  if ((_G.type(case_19_) == "table") and (_G.type(case_19_.mtime) == "table")) then
    OK(string.format(("created abc-lua" or "")))
  else
    local __1_auto = case_19_
    FAIL(string.format(("created abc-lua" or "")))
  end
end
do
  local case_21_ = vim.uv.fs_stat(xyz_lua_path)
  if ((_G.type(case_21_) == "table") and (_G.type(case_21_.mtime) == "table")) then
    OK(string.format(("created xyz-lua" or "")))
  else
    local __1_auto = case_21_
    FAIL(string.format(("created xyz-lua" or "")))
  end
end
local _local_23_ = vim.uv.fs_stat(abc_lua_path)
local abc_time1 = _local_23_.mtime
local _local_24_ = vim.uv.fs_stat(xyz_lua_path)
local xyz_time1 = _local_24_.mtime
vim.uv.sleep(40)
nvim:cmd(("edit " .. abc_fnl_path))
nvim:cmd("write")
local _local_25_ = vim.uv.fs_stat(abc_lua_path)
local abc_time2 = _local_25_.mtime
local _local_26_ = vim.uv.fs_stat(xyz_lua_path)
local xyz_time2 = _local_26_.mtime
do
  local case_27_ = a_newer_than_b_3f(abc_time2, abc_time1)
  if (case_27_ == true) then
    OK(string.format(("rebuilt abc-fnl because it was modified" or "")))
  else
    local __1_auto = case_27_
    FAIL(string.format(("rebuilt abc-fnl because it was modified" or "")))
  end
end
do
  local case_29_ = a_equal_b_3f(xyz_time1, xyz_time2)
  if (case_29_ == true) then
    OK(string.format(("did not rebuild xyz-fnl" or "")))
  else
    local __1_auto = case_29_
    FAIL(string.format(("did not rebuild xyz-fnl" or "")))
  end
end
vim.uv.sleep(40)
nvim:cmd(("edit " .. fnlm_path))
nvim:cmd("write")
local _local_31_ = vim.uv.fs_stat(abc_lua_path)
local abc_time3 = _local_31_.mtime
local _local_32_ = vim.uv.fs_stat(xyz_lua_path)
local xyz_time3 = _local_32_.mtime
do
  local case_33_ = a_newer_than_b_3f(abc_time2, abc_time1)
  if (case_33_ == true) then
    OK(string.format(("rebuilt abc-fnl because of fnlm modified" or "")))
  else
    local __1_auto = case_33_
    FAIL(string.format(("rebuilt abc-fnl because of fnlm modified" or "")))
  end
end
do
  local case_35_ = a_newer_than_b_3f(xyz_time3, xyz_time1)
  if (case_35_ == true) then
    OK(string.format(("rebuilt xyz-fnl because of fnlm modified" or "")))
  else
    local __1_auto = case_35_
    FAIL(string.format(("rebuilt xyz-fnl because of fnlm modified" or "")))
  end
end
vim.uv.sleep(40)
nvim:cmd(("edit " .. ignore_fnlm_path))
nvim:cmd("write")
local _local_37_ = vim.uv.fs_stat(abc_lua_path)
local abc_time4 = _local_37_.mtime
local _local_38_ = vim.uv.fs_stat(xyz_lua_path)
local xyz_time4 = _local_38_.mtime
do
  local case_39_ = a_equal_b_3f(abc_time3, abc_time4)
  if (case_39_ == true) then
    OK(string.format(("did not rebuild abc-fnl when ignored fnlm changed" or "")))
  else
    local __1_auto = case_39_
    FAIL(string.format(("did not rebuild abc-fnl when ignored fnlm changed" or "")))
  end
end
do
  local case_41_ = a_equal_b_3f(xyz_time3, xyz_time4)
  if (case_41_ == true) then
    OK(string.format(("did not rebuild xyz-fnl when ignored fnlm changed" or "")))
  else
    local __1_auto = case_41_
    FAIL(string.format(("did not rebuild xyz-fnl when ignored fnlm changed" or "")))
  end
end
nvim:close()
return exit()