(import-macros {: setup : expect} :test.macros)
(setup)

(fn fixture []
  (local nvim (start-nvim))
  (nvim:lua "_G.called = false
  _G.ret = nil
            vim.ui.select = function(choices, options, callback)
    _G.called = true
    callback('yes', _G.ret)
  end")
  (nvim:lua "require'hotpot'")
  nvim)

;; setup

(create-file (path :config :.hotpot.fnl) "{:schema :hotpot/2 :target :colocate}")
(local fnl-path (create-file (path :config :fnl/user/init.fnl) "{:works true}"))
(local lua-path (path :config :lua/user/init.lua))

(local fnl2-path (create-file (path :config :fnl/user/other.fnl) "{:works true}"))
(local lua2-path (path :config :lua/user/other.lua))

;; create lua files
(local nvim (fixture))
(nvim:cmd "edit %s" fnl-path)
(nvim:cmd "write")
(expect {} (vim.uv.fs_stat lua-path) "did create colocate lua file")
(expect {} (vim.uv.fs_stat lua2-path) "did create colocate lua file 2")

;; remove a source file
(vim.uv.fs_unlink fnl2-path)
(nvim:cmd "write")

;; removed lua counterpart with out asking
(expect {} (vim.uv.fs_stat lua-path) "did keep colocate lua file")
(expect nil (vim.uv.fs_stat lua2-path) "did remove owned colocate lua file 2")
(local [marker] (vim.fn.readfile lua-path))
(expect true (not= nil (string.find marker "-- @generated by hotpot.nvim" 1 true))
        "does write ownership marker to file")

(local vendor-path (create-file (path :config :lua/vendor.lua) "print'hi'"))
(local fnl3-path (create-file (path :config :fnl/user/new.fnl) "{:works true}"))
(local lua3-path (path :config :lua/user/new.lua))

;; 1 list files, 2 clean & compile, 3 dont clean but compile, 4 do nothing
(nvim:lua "_G.ret = 4")
(nvim:lua "_G.called = false")
(nvim:cmd "write")
(local output (nvim:lua "print(_G.called)"))
(expect "true" output "did show confirm prompt")

(expect nil (vim.uv.fs_stat lua3-path) "'cancel' didn't compile file")
(expect {} (vim.uv.fs_stat vendor-path) "'cancel' didn't remove file")

(nvim:lua "_G.ret = 3")
(nvim:lua "_G.called = false")
(nvim:cmd "write")
(local output (nvim:lua "print(_G.called)"))
(expect "true" output "did show confirm prompt")

(expect {} (vim.uv.fs_stat lua3-path) "'dont clean but compile' did compile file")
(expect {} (vim.uv.fs_stat vendor-path) "'dont clean but compile' didn't remove file")


(nvim:lua "_G.ret = 2")
(nvim:lua "_G.called = false")
(nvim:cmd "write")
(local output (nvim:lua "print(_G.called)"))
(expect "true" output "did show confirm prompt")

(expect nil (vim.uv.fs_stat vendor-path) "'clean & compile' removed file")

(nvim:close)

(exit)
