-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local config_path = create_file(path("config", ".hotpot.fnl"), "{:schema :hotpot/2\n                                  :target :colocate\n                                  :ignore [:lua/vendor/lib.lua :fnl/dummy.fnl :fnl/dummy.fnlm]}")
local abc_fnl_path = create_file(path("config", "fnl/abc.fnl"), "{:works true}")
local abc_lua_path = path("config", "lua/abc.lua")
local dummy_fnl_path = create_file(path("config", "fnl/dummy.fnl"), "{:dummy true}")
local dummy_lua_path = path("config", "lua/dummy.lua")
local dummy_fnlm_path = create_file(path("config", "fnl/dummy.fnlm"), "{}")
local vendor_path = create_file(path("config", "lua/vendor/lib.lua"), "return 'vendor lib'")
local nvim = start_nvim()
nvim:lua("require'hotpot'")
do
  local case_2_ = vim.uv.fs_stat(abc_lua_path)
  if ((_G.type(case_2_) == "table") and (_G.type(case_2_.mtime) == "table")) then
    OK(string.format(("created abc-lua" or "")))
  else
    local __1_auto = case_2_
    FAIL(string.format(("created abc-lua" or "")))
  end
end
do
  local case_4_ = vim.uv.fs_stat(vendor_path)
  if ((_G.type(case_4_) == "table") and (_G.type(case_4_.mtime) == "table")) then
    OK(string.format(("retained vendor-lua" or "")))
  else
    local __1_auto = case_4_
    FAIL(string.format(("retained vendor-lua" or "")))
  end
end
do
  local case_6_ = vim.uv.fs_stat(dummy_lua_path)
  if (case_6_ == nil) then
    OK(string.format(("did not create dummy-lua" or "")))
  else
    local __1_auto = case_6_
    FAIL(string.format(("did not create dummy-lua" or "")))
  end
end
local _local_8_ = vim.uv.fs_stat(abc_lua_path)
local _local_9_ = _local_8_.mtime
local time1 = _local_9_.sec
nvim:cmd(("edit " .. dummy_fnl_path))
nvim:cmd("write")
local _local_10_ = vim.uv.fs_stat(abc_lua_path)
local _local_11_ = _local_10_.mtime
local time2 = _local_11_.sec
do
  local case_12_ = vim.uv.fs_stat(dummy_lua_path)
  if (case_12_ == nil) then
    OK(string.format(("did not create dummy-lua after write" or "")))
  else
    local __1_auto = case_12_
    FAIL(string.format(("did not create dummy-lua after write" or "")))
  end
end
do
  local case_14_ = (time1 == time2)
  if (case_14_ == true) then
    OK(string.format(("did not rebuild abc-lua with no changes" or "")))
  else
    local __1_auto = case_14_
    FAIL(string.format(("did not rebuild abc-lua with no changes" or "")))
  end
end
nvim:close()
return exit()