-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local config_path = create_file(path("config", ".hotpot.fnl"), "{:schema :hotpot/2 :target :colocate}")
local fnl_path = create_file(path("config", "fnl/abc.fnl"), "{:works true}")
local lua_path = path("config", "/lua/abc.lua")
local nvim = start_nvim()
nvim:lua("require'hotpot'")
nvim:close()
do
  local case_2_ = read_file(lua_path)
  if ((_G.type(case_2_) == "table") and true and (case_2_[2] == "return {works = true}")) then
    local _ = case_2_[1]
    OK(string.format(("created lua file in colocate" or "")))
  else
    local __1_auto = case_2_
    FAIL(string.format(("created lua file in colocate" or "")))
  end
end
return exit()