-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local fnl_path = create_file(path("config", "init.fnl"), "{:works true}")
local nvim = start_nvim()
nvim:lua("_G.called = false\n          vim.ui.select = function(choices, options, callback)\n  _G.called = true\n  callback('yes', 1)\nend")
nvim:lua("require'hotpot'")
nvim:cmd("edit %s", fnl_path)
nvim:cmd("write")
local output = nvim:lua("print(_G.called)")
if (output == "true") then
  OK(string.format(("Did call ui prompt" or "")))
else
  local __1_auto = output
  FAIL(string.format(("Did call ui prompt" or "")))
end
nvim:close()
return exit()