-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local nvim = start_nvim()
nvim:lua("require'hotpot'")
local output = nvim:cmd("Fnl= (+ 1 1)")
if (output == "2") then
  OK(string.format((":Fnl= evaluates and prints result" or "")))
else
  local __1_auto = output
  FAIL(string.format((":Fnl= evaluates and prints result" or "")))
end
local output0 = nvim:cmd("Fnl (+ 1 1)")
if (output0 == "") then
  OK(string.format((":Fnl evals without printing" or "")))
else
  local __1_auto = output0
  FAIL(string.format((":Fnl evals without printing" or "")))
end
local output1 = nvim:cmd("Fnl (print (+ 1 1))")
if (output1 == "2") then
  OK(string.format((":Fnl with print evals and prints" or "")))
else
  local __1_auto = output1
  FAIL(string.format((":Fnl with print evals and prints" or "")))
end
local output2 = nvim:cmd("Fnl- (+ 1 1)")
if (output2 == "return (1 + 1)") then
  OK(string.format((":Fnl- compiles and prints lua" or "")))
else
  local __1_auto = output2
  FAIL(string.format((":Fnl- compiles and prints lua" or "")))
end
local output3 = nvim:cmd("FnlEval (+ 1 1)")
if (output3 == "2") then
  OK(string.format((":FnlEval evaluates and prints result" or "")))
else
  local __1_auto = output3
  FAIL(string.format((":FnlEval evaluates and prints result" or "")))
end
local output4 = nvim:cmd("FnlCompile (+ 1 1)")
if (output4 == "return (1 + 1)") then
  OK(string.format((":FnlCompile compiles and prints lua" or "")))
else
  local __1_auto = output4
  FAIL(string.format((":FnlCompile compiles and prints lua" or "")))
end
nvim:close()
return exit()