-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local remote_dir = vim.fs.normalize("~/remote")
vim.fn.mkdir((remote_dir .. "/fnl"), "p")
create_file((remote_dir .. "/.hotpot.fnl"), "{:schema :hotpot/2 :target :colocate}")
create_file((remote_dir .. "/fnl/mod.fnl"), "(import-macros {: x} :macros) (x)")
create_file(path("config", "/fnl/macros.fnlm"), "{:x (fn [] `:config-x)}")
local nvim = start_nvim()
nvim:lua("require'hotpot'")
nvim:cmd(("edit " .. (remote_dir .. "/fnl/mod.fnl")))
nvim:cmd(("cd " .. path("config")))
nvim:cmd("write")
nvim:close()
do
  local case_2_ = vim.uv.fs_stat((remote_dir .. "/lua/mod.lua"))
  if (_G.type(case_2_) == "table") then
    OK(string.format(("creates lua/mod.lua in non cwd" or "")))
  else
    local __1_auto = case_2_
    FAIL(string.format(("creates lua/mod.lua in non cwd" or "")))
  end
end
vim.uv.sleep(5)
create_file((remote_dir .. "/fnl/macros.fnlm"), "{:x (fn [] `:remote-x)}")
local nvim0 = start_nvim()
nvim0:lua("require'hotpot'")
nvim0:cmd(("edit " .. (remote_dir .. "/fnl/mod.fnl")))
nvim0:cmd(("cd " .. path("config")))
nvim0:cmd("write")
nvim0:close()
do
  local case_4_ = read_file((remote_dir .. "/lua/mod.lua"))
  if ((_G.type(case_4_) == "table") and true and (case_4_[2] == "return \"remote-x\"")) then
    local _ = case_4_[1]
    OK(string.format(("correctly uses remote.macros.x()" or "")))
  else
    local __1_auto = case_4_
    FAIL(string.format(("correctly uses remote.macros.x()" or "")))
  end
end
return exit()