-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local function fixture()
  local nvim = start_nvim()
  nvim:lua("_G.called = false\n  _G.ret = nil\n            vim.ui.select = function(choices, options, callback)\n    _G.called = true\n    callback('yes', _G.ret)\n  end")
  nvim:lua("require'hotpot'")
  return nvim
end
create_file(path("config", ".hotpot.fnl"), "{:schema :hotpot/2 :target :colocate}")
local fnl_path = create_file(path("config", "fnl/user/init.fnl"), "{:works true}")
local lua_path = path("config", "lua/user/init.lua")
local fnl2_path = create_file(path("config", "fnl/user/other.fnl"), "{:works true}")
local lua2_path = path("config", "lua/user/other.lua")
local nvim = fixture()
nvim:cmd("edit %s", fnl_path)
nvim:cmd("write")
do
  local case_2_ = vim.uv.fs_stat(lua_path)
  if (_G.type(case_2_) == "table") then
    OK(string.format(("did create colocate lua file" or "")))
  else
    local __1_auto = case_2_
    FAIL(string.format(("did create colocate lua file" or "")))
  end
end
do
  local case_4_ = vim.uv.fs_stat(lua2_path)
  if (_G.type(case_4_) == "table") then
    OK(string.format(("did create colocate lua file 2" or "")))
  else
    local __1_auto = case_4_
    FAIL(string.format(("did create colocate lua file 2" or "")))
  end
end
vim.uv.fs_unlink(fnl2_path)
nvim:cmd("write")
do
  local case_6_ = vim.uv.fs_stat(lua_path)
  if (_G.type(case_6_) == "table") then
    OK(string.format(("did keep colocate lua file" or "")))
  else
    local __1_auto = case_6_
    FAIL(string.format(("did keep colocate lua file" or "")))
  end
end
do
  local case_8_ = vim.uv.fs_stat(lua2_path)
  if (case_8_ == nil) then
    OK(string.format(("did remove owned colocate lua file 2" or "")))
  else
    local __1_auto = case_8_
    FAIL(string.format(("did remove owned colocate lua file 2" or "")))
  end
end
local _local_10_ = vim.fn.readfile(lua_path)
local marker = _local_10_[1]
do
  local case_11_ = (nil ~= string.find(marker, "-- @generated by hotpot.nvim", 1, true))
  if (case_11_ == true) then
    OK(string.format(("does write ownership marker to file" or "")))
  else
    local __1_auto = case_11_
    FAIL(string.format(("does write ownership marker to file" or "")))
  end
end
local vendor_path = create_file(path("config", "lua/vendor.lua"), "print'hi'")
local fnl3_path = create_file(path("config", "fnl/user/new.fnl"), "{:works true}")
local lua3_path = path("config", "lua/user/new.lua")
nvim:lua("_G.ret = 4")
nvim:lua("_G.called = false")
nvim:cmd("write")
local output = nvim:lua("print(_G.called)")
if (output == "true") then
  OK(string.format(("did show confirm prompt" or "")))
else
  local __1_auto = output
  FAIL(string.format(("did show confirm prompt" or "")))
end
do
  local case_14_ = vim.uv.fs_stat(lua3_path)
  if (case_14_ == nil) then
    OK(string.format(("'cancel' didn't compile file" or "")))
  else
    local __1_auto = case_14_
    FAIL(string.format(("'cancel' didn't compile file" or "")))
  end
end
do
  local case_16_ = vim.uv.fs_stat(vendor_path)
  if (_G.type(case_16_) == "table") then
    OK(string.format(("'cancel' didn't remove file" or "")))
  else
    local __1_auto = case_16_
    FAIL(string.format(("'cancel' didn't remove file" or "")))
  end
end
nvim:lua("_G.ret = 3")
nvim:lua("_G.called = false")
nvim:cmd("write")
local output0 = nvim:lua("print(_G.called)")
if (output0 == "true") then
  OK(string.format(("did show confirm prompt" or "")))
else
  local __1_auto = output0
  FAIL(string.format(("did show confirm prompt" or "")))
end
do
  local case_19_ = vim.uv.fs_stat(lua3_path)
  if (_G.type(case_19_) == "table") then
    OK(string.format(("'dont clean but compile' did compile file" or "")))
  else
    local __1_auto = case_19_
    FAIL(string.format(("'dont clean but compile' did compile file" or "")))
  end
end
do
  local case_21_ = vim.uv.fs_stat(vendor_path)
  if (_G.type(case_21_) == "table") then
    OK(string.format(("'dont clean but compile' didn't remove file" or "")))
  else
    local __1_auto = case_21_
    FAIL(string.format(("'dont clean but compile' didn't remove file" or "")))
  end
end
nvim:lua("_G.ret = 2")
nvim:lua("_G.called = false")
nvim:cmd("write")
local output1 = nvim:lua("print(_G.called)")
if (output1 == "true") then
  OK(string.format(("did show confirm prompt" or "")))
else
  local __1_auto = output1
  FAIL(string.format(("did show confirm prompt" or "")))
end
do
  local case_24_ = vim.uv.fs_stat(vendor_path)
  if (case_24_ == nil) then
    OK(string.format(("'clean & compile' removed file" or "")))
  else
    local __1_auto = case_24_
    FAIL(string.format(("'clean & compile' removed file" or "")))
  end
end
nvim:close()
return exit()