-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local fnl_path = create_file(path("config", "/fnl/abc.fnl"), "{:works true}")
local first_boot_sigil = path("cache")
local lua_path = path("cache", "/lua/abc.lua")
do
  local case_2_ = vim.uv.fs_stat(first_boot_sigil)
  if (case_2_ == nil) then
    OK(string.format(("no first-boot-sigil" or "")))
  else
    local __1_auto = case_2_
    FAIL(string.format(("no first-boot-sigil" or "")))
  end
end
local nvim = start_nvim()
nvim:lua("require'hotpot'")
nvim:close()
do
  local case_4_ = vim.uv.fs_stat(first_boot_sigil)
  if ((_G.type(case_4_) == "table") and (_G.type(case_4_.mtime) == "table")) then
    OK(string.format(("created first-boot-sigil" or "")))
  else
    local __1_auto = case_4_
    FAIL(string.format(("created first-boot-sigil" or "")))
  end
end
do
  local case_6_ = read_file(lua_path)
  if ((_G.type(case_6_) == "table") and true and (case_6_[2] == "return {works = true}")) then
    local _ = case_6_[1]
    OK(string.format(("created lua file in cache" or "")))
  else
    local __1_auto = case_6_
    FAIL(string.format(("created lua file in cache" or "")))
  end
end
return exit()