-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
create_file(path("config", ".hotpot.fnl"), "{:schema :hotpot/2 :target :colocate}")
local fnl_path = create_file(path("config", "fnl/mymod.fnl"), "{:works true}")
local lua_path = path("config", "lua/mymod.lua")
local nvim = start_nvim()
nvim:lua("require'hotpot'")
local output = nvim:cmd("Hotpot locate %s", fnl_path)
if (nil ~= output) then
  local lua_path0 = output
  OK(string.format((":Hotpot locate <path> echos counterpart path" or "")))
else
  local __1_auto = output
  FAIL(string.format((":Hotpot locate <path> echos counterpart path" or "")))
end
nvim:cmd("edit %s", fnl_path)
local output0 = nvim:cmd("Hotpot locate")
if (nil ~= output0) then
  local lua_path0 = output0
  OK(string.format((":Hotpot locate echos counterpart path for current file" or "")))
else
  local __1_auto = output0
  FAIL(string.format((":Hotpot locate echos counterpart path for current file" or "")))
end
nvim:cmd("Hotpot locate -- vnew")
local buf_name = nvim:lua("print(vim.api.nvim_buf_get_name(0))")
if (nil ~= buf_name) then
  local lua_path0 = buf_name
  OK(string.format((":Hotpot locate <fnl-path> -- vnew opens lua counterpart in new window" or "")))
else
  local __1_auto = buf_name
  FAIL(string.format((":Hotpot locate <fnl-path> -- vnew opens lua counterpart in new window" or "")))
end
nvim:cmd("Hotpot locate -- vnew")
local output1 = nvim:cmd("Hotpot locate")
if (nil ~= output1) then
  local fnl_path0 = output1
  OK(string.format((":Hotpot locate <lua-path> returns fnl path in colocate context" or "")))
else
  local __1_auto = output1
  FAIL(string.format((":Hotpot locate <lua-path> returns fnl path in colocate context" or "")))
end
local output2 = nvim:cmd("Hotpot locate", fnl_path)
vim.print(output2)
nvim:close()
return exit()