-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local config_path = create_file(path("config", ".hotpot.fnl"), "{:schema :hotpot/2\n                                  :target :colocate\n                                  :ignore [:fnl/ignore.fnlm]}")
local abc_fnl_path = create_file(path("config", "fnl/abc.fnl"), "{:works true}")
local abc_lua_path = path("config", "lua/abc.lua")
local xyz_fnl_path = create_file(path("config", "fnl/xyz.fnl"), "{:works true}")
local xyz_lua_path = path("config", "lua/xyz.lua")
local fnlm_path = create_file(path("config", "fnl/macro.fnlm"), "{}")
local ignore_fnlm_path = create_file(path("config", "fnl/ignore.fnlm"), "{}")
local function a_newer_than_b_3f(mtime1, mtime2)
  local s1 = mtime1.sec
  local n1 = mtime1.nsec
  local s2 = mtime2.sec
  local n2 = mtime2.nsec
  return (((s2 == s1) and (n2 < n1)) or (s2 < s1))
end
local function a_equal_b_3f(mtime1, mtime2)
  local s1 = mtime1.sec
  local n1 = mtime1.nsec
  local s2 = mtime2.sec
  local n2 = mtime2.nsec
  return ((s1 == s2) and (n1 == n2))
end
local nvim = start_nvim()
nvim:lua("require'hotpot'")
do
  local case_2_ = vim.uv.fs_stat(abc_lua_path)
  if ((_G.type(case_2_) == "table") and (_G.type(case_2_.mtime) == "table")) then
    OK(string.format(("created abc-lua" or "")))
  else
    local __1_auto = case_2_
    FAIL(string.format(("created abc-lua" or "")))
  end
end
do
  local case_4_ = vim.uv.fs_stat(xyz_lua_path)
  if ((_G.type(case_4_) == "table") and (_G.type(case_4_.mtime) == "table")) then
    OK(string.format(("created xyz-lua" or "")))
  else
    local __1_auto = case_4_
    FAIL(string.format(("created xyz-lua" or "")))
  end
end
local _local_6_ = vim.uv.fs_stat(abc_lua_path)
local abc_time1 = _local_6_.mtime
local _local_7_ = vim.uv.fs_stat(xyz_lua_path)
local xyz_time1 = _local_7_.mtime
vim.uv.sleep(40)
nvim:cmd(("edit " .. abc_fnl_path))
nvim:cmd("write")
local _local_8_ = vim.uv.fs_stat(abc_lua_path)
local abc_time2 = _local_8_.mtime
local _local_9_ = vim.uv.fs_stat(xyz_lua_path)
local xyz_time2 = _local_9_.mtime
do
  local case_10_ = a_newer_than_b_3f(abc_time2, abc_time1)
  if (case_10_ == true) then
    OK(string.format(("rebuilt abc-fnl because it was modified" or "")))
  else
    local __1_auto = case_10_
    FAIL(string.format(("rebuilt abc-fnl because it was modified" or "")))
  end
end
do
  local case_12_ = a_equal_b_3f(xyz_time1, xyz_time2)
  if (case_12_ == true) then
    OK(string.format(("did not rebuild xyz-fnl" or "")))
  else
    local __1_auto = case_12_
    FAIL(string.format(("did not rebuild xyz-fnl" or "")))
  end
end
vim.uv.sleep(40)
nvim:cmd(("edit " .. fnlm_path))
nvim:cmd("write")
local _local_14_ = vim.uv.fs_stat(abc_lua_path)
local abc_time3 = _local_14_.mtime
local _local_15_ = vim.uv.fs_stat(xyz_lua_path)
local xyz_time3 = _local_15_.mtime
do
  local case_16_ = a_newer_than_b_3f(abc_time2, abc_time1)
  if (case_16_ == true) then
    OK(string.format(("rebuilt abc-fnl because of fnlm modified" or "")))
  else
    local __1_auto = case_16_
    FAIL(string.format(("rebuilt abc-fnl because of fnlm modified" or "")))
  end
end
do
  local case_18_ = a_newer_than_b_3f(xyz_time3, xyz_time1)
  if (case_18_ == true) then
    OK(string.format(("rebuilt xyz-fnl because of fnlm modified" or "")))
  else
    local __1_auto = case_18_
    FAIL(string.format(("rebuilt xyz-fnl because of fnlm modified" or "")))
  end
end
vim.uv.sleep(40)
nvim:cmd(("edit " .. ignore_fnlm_path))
nvim:cmd("write")
local _local_20_ = vim.uv.fs_stat(abc_lua_path)
local abc_time4 = _local_20_.mtime
local _local_21_ = vim.uv.fs_stat(xyz_lua_path)
local xyz_time4 = _local_21_.mtime
do
  local case_22_ = a_equal_b_3f(abc_time3, abc_time4)
  if (case_22_ == true) then
    OK(string.format(("did not rebuild abc-fnl when ignored fnlm changed" or "")))
  else
    local __1_auto = case_22_
    FAIL(string.format(("did not rebuild abc-fnl when ignored fnlm changed" or "")))
  end
end
do
  local case_24_ = a_equal_b_3f(xyz_time3, xyz_time4)
  if (case_24_ == true) then
    OK(string.format(("did not rebuild xyz-fnl when ignored fnlm changed" or "")))
  else
    local __1_auto = case_24_
    FAIL(string.format(("did not rebuild xyz-fnl when ignored fnlm changed" or "")))
  end
end
nvim:close()
return exit()