-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("test.utils")
local FAIL = _local_1_.FAIL
local NVIM_APPNAME = _local_1_.NVIM_APPNAME
local OK = _local_1_.OK
local create_file = _local_1_["create-file"]
local exit = _local_1_.exit
local path = _local_1_.path
local read_file = _local_1_["read-file"]
local start_nvim = _local_1_["start-nvim"]
local write_file = _local_1_["write-file"]
local config_path = create_file(path("config", ".hotpot.fnl"), "{:schema :hotpot/2 :target :cache}")
local fnl_path = create_file(path("config", "fnl/abc.fnl"), "{:works true}")
local lua_path = path("cache", "/lua/abc.lua")
local vendor_path = create_file(path("config", "lua/vendor/lib.lua"), "return 'vendor lib'")
local nvim = start_nvim()
nvim:lua("require'hotpot'")
nvim:close()
do
  local case_2_ = read_file(lua_path)
  if ((_G.type(case_2_) == "table") and true and (case_2_[2] == "return {works = true}")) then
    local _ = case_2_[1]
    OK(string.format(("first boot created lua file in cache" or "")))
  else
    local __1_auto = case_2_
    FAIL(string.format(("first boot created lua file in cache" or "")))
  end
end
do
  local case_4_ = read_file(vendor_path)
  if ((_G.type(case_4_) == "table") and (case_4_[1] == "return 'vendor lib'")) then
    OK(string.format(("first boot left vendor file untouched" or "")))
  else
    local __1_auto = case_4_
    FAIL(string.format(("first boot left vendor file untouched" or "")))
  end
end
local fnl_path2 = create_file(path("config", "fnl/xyz.fnl"), "{:works :also}")
local lua_path2 = path("cache", "/lua/xyz.lua")
local nvim0 = start_nvim()
nvim0:lua("require'hotpot'")
do
  local case_6_ = read_file(lua_path)
  if ((_G.type(case_6_) == "table") and true and (case_6_[2] == "return {works = true}")) then
    local _ = case_6_[1]
    OK(string.format(("second boot kept lua file in cache" or "")))
  else
    local __1_auto = case_6_
    FAIL(string.format(("second boot kept lua file in cache" or "")))
  end
end
do
  local case_8_ = vim.uv.fs_stat(lua_path2)
  if (case_8_ == nil) then
    OK(string.format(("second boot did not create second file in cache" or "")))
  else
    local __1_auto = case_8_
    FAIL(string.format(("second boot did not create second file in cache" or "")))
  end
end
do
  local case_10_ = read_file(vendor_path)
  if ((_G.type(case_10_) == "table") and (case_10_[1] == "return 'vendor lib'")) then
    OK(string.format(("second boot left vendor file untouched" or "")))
  else
    local __1_auto = case_10_
    FAIL(string.format(("second boot left vendor file untouched" or "")))
  end
end
nvim0:cmd(("edit " .. fnl_path2))
nvim0:cmd("write")
do
  local case_12_ = read_file(lua_path)
  if ((_G.type(case_12_) == "table") and true and (case_12_[2] == "return {works = true}")) then
    local _ = case_12_[1]
    OK(string.format(("saving file kept lua file in cache" or "")))
  else
    local __1_auto = case_12_
    FAIL(string.format(("saving file kept lua file in cache" or "")))
  end
end
do
  local case_14_ = read_file(lua_path2)
  if ((_G.type(case_14_) == "table") and true and (case_14_[2] == "return {works = \"also\"}")) then
    local _ = case_14_[1]
    OK(string.format(("saving file created lua file 2 in cache" or "")))
  else
    local __1_auto = case_14_
    FAIL(string.format(("saving file created lua file 2 in cache" or "")))
  end
end
do
  local case_16_ = read_file(vendor_path)
  if ((_G.type(case_16_) == "table") and (case_16_[1] == "return 'vendor lib'")) then
    OK(string.format(("saving file left vendor file untouched" or "")))
  else
    local __1_auto = case_16_
    FAIL(string.format(("saving file left vendor file untouched" or "")))
  end
end
vim.fn.delete(fnl_path)
nvim0:cmd("write")
do
  local case_18_ = vim.uv.fs_stat(lua_path)
  if (case_18_ == nil) then
    OK(string.format(("saving file removed orphaned file" or "")))
  else
    local __1_auto = case_18_
    FAIL(string.format(("saving file removed orphaned file" or "")))
  end
end
do
  local case_20_ = read_file(lua_path2)
  if ((_G.type(case_20_) == "table") and true and (case_20_[2] == "return {works = \"also\"}")) then
    local _ = case_20_[1]
    OK(string.format(("saving file retained lua file 2 in cache" or "")))
  else
    local __1_auto = case_20_
    FAIL(string.format(("saving file retained lua file 2 in cache" or "")))
  end
end
do
  local case_22_ = read_file(vendor_path)
  if ((_G.type(case_22_) == "table") and (case_22_[1] == "return 'vendor lib'")) then
    OK(string.format(("saving file left vendor file untouched" or "")))
  else
    local __1_auto = case_22_
    FAIL(string.format(("saving file left vendor file untouched" or "")))
  end
end
nvim0:close()
return exit()