#!/usr/bin/env sh

snag() {
  # clean
  rm -rf lua/

  # You are OBSOLETE
  # create destinations
  # for dir in $(fd -td ".*" fnl)
  # do
  #   mkdir -p ${dir/fnl/lua}
  # done

  # you are also OBSOLETE
  # build
  # for src in $(fd -tf fnl)
  # do
  #   case "$src" in
  #     # dont actually build macrofile
  #     *hotpot/macros.fnl*) echo "ignoring $src" ;;
  #     # add path so we can run from project root
  #     *) fennel --add-fennel-path "fnl/?.fnl" --compile --correlate $src > ${src//fnl/lua};;
  #   esac
  # done

  # you are a precious delicate flower and must be preserved

  mkdir -p lua/hotpot
  cp dep/fennel.lua lua/hotpot/fennel.lua
  # don't tell them what's in the pot...
  fennel --compile dogfood.fnl > lua/hotpot.lua
}

snag2() {
  # clean
  rm -rf lua/

  # create destinations
  for dir in $(fd -td ".*" fnl)
  do
    mkdir -p ${dir/fnl/lua}
  done

  # you are also OBSOLETE
  # build
  for src in $(fd -tf fnl fnl/)
  do
    case "$src" in
      # dont actually build macrofile
      *hotpot/macros.fnl*) echo "ignoring $src" ;;
      # add path so we can run from project root
      *) fennel --add-fennel-path "fnl/?.fnl" --compile $src > ${src//fnl/lua};;
    esac
  done

  # you are a precious delicate flower and must be preserved

  # mkdir -p lua/hotpot
  cp dep/fennel.lua lua/hotpot/fennel.lua
  # don't need loader hook
  mv lua/hotpot/hotterpot.lua lua/hotpot.lua
  # don't tell them what's in the pot...
  #fennel --compile --indent "  " --correlate dogfood.fnl > lua/hotpot.lua
  echo "$(date) built"
}

beer() {
  # yeah looks good mate
  # fd -tf fnl | entr -sc './barbie snag'
  fd -tf fnl | entr -sc './barbie snag'
}

beer2() {
  # yeah looks good mate
  # fd -tf fnl | entr -sc './barbie snag'
  fd -tf fnl | entr -sc './barbie snag2'
}

release() {
  canary=$(tar --exclude canary/ -cf - . | sha1sum | cut -d' ' -f1)
  rm -rf canary/
  mkdir -p canary/
  touch canary/$canary
}

case "$1" in
  "release")
    release
    exit 0;;
  "snag")
    snag
    release
    exit 0;;
  "snag2")
    snag2
    release
    exit 0;;
  "beer")
    beer
    release
    exit 0;;
  "beer2")
    beer2
    release
    exit 0;;
  *)
    echo "$0 snag|beer";;
esac
