-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
if (nil == _G.__hotpot_disable_version_check) then
  assert((1 == vim.fn.has("nvim-0.11.6")), "Hotpot requires neovim 0.11.6")
else
end
local _local_2_ = require("hotpot.util")
local R = _local_2_.R
local notify_error = _local_2_["notify-error"]
local notify_warn = _local_2_["notify-warn"]
local notify_info = _local_2_["notify-info"]
local HOTPOT_CONFIG_CACHE_ROOT = R.const.HOTPOT_CONFIG_CACHE_ROOT
local HOTPOT_FENNEL_UPDATE_ROOT = R.const.HOTPOT_FENNEL_UPDATE_ROOT
local HOTPOT_FENNEL_UPDATE_LUA_ROOT = R.const.HOTPOT_FENNEL_UPDATE_LUA_ROOT
do
  local case_3_ = vim.uv.fs_stat(HOTPOT_CONFIG_CACHE_ROOT)
  if (case_3_ == nil) then
    local _ = vim.fn.mkdir(HOTPOT_CONFIG_CACHE_ROOT, "p")
    local Context = R.Context
    local function _4_(...)
      local case_5_, case_6_ = ...
      if ((case_5_ == true) and (nil ~= case_6_)) then
        local ctx = case_6_
        local function _7_(...)
          local case_8_, case_9_ = ...
          if (case_8_ == true) then
            return "ok"
          elseif ((case_8_ == false) and (nil ~= case_9_)) then
            local err = case_9_
            notify_warn("Hotpot encountered an error syncing during first-time startup.")
            notify_warn("You should still be able to edit fnl files to fixe the issue.")
            return notify_error(err)
          else
            return nil
          end
        end
        return _7_(pcall(Context.sync, ctx))
      elseif ((case_5_ == false) and (nil ~= case_6_)) then
        local err = case_6_
        notify_warn("Hotpot encountered an error syncing during first-time startup.")
        notify_warn("You should still be able to edit fnl files to fixe the issue.")
        return notify_error(err)
      else
        return nil
      end
    end
    _4_(pcall(Context.new, vim.fn.stdpath("config")))
  elseif ((_G.type(case_3_) == "table") and (case_3_.type == "directory")) then
  elseif ((_G.type(case_3_) == "table") and (nil ~= case_3_.type)) then
    local t = case_3_.type
    notify_error(table.concat({"Hotpot: %s exists but is not directory, is %s, consider removing it?", "Hotpot probably wont function correctly."}, "\n"), HOTPOT_CONFIG_CACHE_ROOT, t)
  else
  end
end
do
  local autocmd = R.autocmd
  local command = R.command
  autocmd.enable()
  command.enable()
end
do
  local function _13_()
    return require("hotpot.fennel")
  end
  package.preload["fennel"] = _13_
end
do
  local bang = (0 == vim.v.vim_did_init)
  do
    local case_14_ = vim.uv.fs_stat(HOTPOT_FENNEL_UPDATE_LUA_ROOT)
    if (case_14_ == nil) then
      vim.fn.mkdir(HOTPOT_FENNEL_UPDATE_LUA_ROOT, "p")
    else
    end
  end
  vim.cmd.packadd({vim.fs.basename(HOTPOT_FENNEL_UPDATE_ROOT), bang = bang})
  vim.cmd.packadd({vim.fs.basename(HOTPOT_CONFIG_CACHE_ROOT), bang = bang})
end
local function setup(_3foptions)
  return true
end
return {setup = setup}