-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
assert((1 == vim.fn.has("nvim-0.11.6")), "Hotpot requires neovim 0.11.6+")
local _local_1_ = require("hotpot.util")
local R = _local_1_.R
local notify_error = _local_1_["notify-error"]
local notify_warn = _local_1_["notify-warn"]
local HOTPOT_CONFIG_CACHE_ROOT = R.const.HOTPOT_CONFIG_CACHE_ROOT
local HOTPOT_FENNEL_UPDATE_ROOT = R.const.HOTPOT_FENNEL_UPDATE_ROOT
local HOTPOT_FENNEL_UPDATE_LUA_ROOT = R.const.HOTPOT_FENNEL_UPDATE_LUA_ROOT
do
  local case_2_ = vim.uv.fs_stat(HOTPOT_CONFIG_CACHE_ROOT)
  if (case_2_ == nil) then
    local _ = vim.fn.mkdir(HOTPOT_CONFIG_CACHE_ROOT, "p")
    local Context = R.Context
    local case_3_, case_4_ = pcall(Context.new, vim.fn.stdpath("config"))
    if ((case_3_ == true) and (nil ~= case_4_)) then
      local ctx = case_4_
      local case_5_ = Context.sync(ctx)
      if ((_G.type(case_5_) == "table") and ((_G.type(case_5_.errors) == "table") and (case_5_.errors[1] == nil))) then
      elseif (nil ~= case_5_) then
        local report = case_5_
        R.Runtime["invoke-sync-report-handler"](ctx, report, {reason = "boot"})
      else
      end
    elseif ((case_3_ == false) and (nil ~= case_4_)) then
      local err = case_4_
      notify_error(err)
    else
    end
  elseif ((_G.type(case_2_) == "table") and (case_2_.type == "directory")) then
  elseif ((_G.type(case_2_) == "table") and (nil ~= case_2_.type)) then
    local t = case_2_.type
    notify_error(table.concat({"Hotpot: %s exists but is not directory, is %s, consider removing it?", "Hotpot probably wont function correctly."}, "\n"), HOTPOT_CONFIG_CACHE_ROOT, t)
  else
  end
end
do
  local autocmd = R.autocmd
  local command = R.command
  autocmd.enable()
  command.enable()
end
local function _9_()
  return require("hotpot.fennel")
end
package.preload.fennel = _9_
do
  local bang = (0 == vim.v.vim_did_init)
  do
    local case_10_ = vim.uv.fs_stat(HOTPOT_FENNEL_UPDATE_LUA_ROOT)
    if (case_10_ == nil) then
      vim.fn.mkdir(HOTPOT_FENNEL_UPDATE_LUA_ROOT, "p")
    else
    end
  end
  vim.cmd.packadd({vim.fs.basename(HOTPOT_FENNEL_UPDATE_ROOT), bang = bang})
  vim.cmd.packadd({vim.fs.basename(HOTPOT_CONFIG_CACHE_ROOT), bang = bang})
end
local function setup(_3foptions)
  local opts
  do
    local tbl_21_ = {}
    for key, val in pairs((_3foptions or {})) do
      local k_22_, v_23_ = string.gsub(key, "_", "-"), val
      if ((k_22_ ~= nil) and (v_23_ ~= nil)) then
        tbl_21_[k_22_] = v_23_
      else
      end
    end
    opts = tbl_21_
  end
  local case_13_, case_14_ = R.runtime.apply(opts)
  if (case_13_ == true) then
    return true
  elseif ((case_13_ == false) and (nil ~= case_14_)) then
    local err = case_14_
    return notify_warn(("Invalid configuration provided to `hotpot.setup`: \n" .. err))
  else
    return nil
  end
end
return {setup = setup}