-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("hotpot.util")
local R = _local_1_.R
local M, m = {}, {}
local function bind_compile(ctx)
  local function _2_(source, _3foptions)
    if (nil == source) then
      _G.error("Missing argument source on fnl/hotpot/api.fnl:9", 2)
    else
    end
    return pcall(R.context["compile-string"], ctx, source, vim.tbl_extend("force", (_3foptions or {}), {filename = "--hotpot-api-compile"}))
  end
  return _2_
end
local function bind_eval(ctx)
  local function _4_(source, _3foptions)
    if (nil == source) then
      _G.error("Missing argument source on fnl/hotpot/api.fnl:17", 2)
    else
    end
    return pcall(R.context["eval-string"], ctx, source, vim.tbl_extend("force", (_3foptions or {}), {filename = "--hotpot-api-eval"}))
  end
  return _4_
end
local function bind_sync(ctx)
  if ((_G.type(ctx) == "table") and (ctx.kind == "api")) then
    return nil
  else
    local _ = ctx
    local function _6_(_3foptions)
      local case_7_, case_8_ = pcall(R.context.sync, ctx, _3foptions)
      if ((case_7_ == true) and (nil ~= case_8_)) then
        local report = case_8_
        return R.runtime["invoke-sync-report-handler"](ctx, report, {reason = "api"})
      elseif ((case_7_ == false) and true) then
        local _3ferr = case_8_
        return false, _3ferr
      else
        return nil
      end
    end
    return _6_
  end
end
local function bind_locate(ctx)
  if ((_G.type(ctx) == "table") and (ctx.kind == "api")) then
    return nil
  else
    local _ = ctx
    local function _11_(what)
      if (nil == what) then
        _G.error("Missing argument what on fnl/hotpot/api.fnl:35", 2)
      else
      end
      if (what == "source") then
        return ctx.path.source
      elseif (what == "destination") then
        return ctx.path.dest
      else
        local and_13_ = (nil ~= what)
        if and_13_ then
          local path = what
          and_13_ = ("string" == type(path))
        end
        if and_13_ then
          local path = what
          local real_path = (vim.uv.fs_realpath(path) or path)
          local _let_15_ = R.const
          local NVIM_CONFIG_ROOT = _let_15_.NVIM_CONFIG_ROOT
          local init_fnl = vim.fs.joinpath(NVIM_CONFIG_ROOT, "init.fnl")
          local init_lua = vim.fs.joinpath(NVIM_CONFIG_ROOT, "init.lua")
          local ext = string.match(real_path, "%.([^%.]+)$")
          local case_16_, case_17_ = real_path, ext
          local and_18_ = (case_16_ == init_fnl)
          if and_18_ then
            and_18_ = _
          end
          if and_18_ then
            return init_lua
          else
            local and_20_ = (case_16_ == init_lua)
            if and_20_ then
              and_20_ = _
            end
            if and_20_ then
              return init_fnl
            elseif (true and (case_17_ == "fnlm")) then
              local _0 = case_16_
              return real_path
            elseif (true and (case_17_ == "fnl")) then
              local _0 = case_16_
              local case_22_ = vim.fs.relpath(ctx.path.source, path)
              if (nil ~= case_22_) then
                local rel_path = case_22_
                local renamed = string.gsub(string.gsub(rel_path, "^fnl/", "lua/"), "%.fnl$", ".lua")
                return vim.fs.joinpath(ctx.path.dest, renamed)
              elseif (case_22_ == nil) then
                return nil, string.format("%s not under context source %s", path, ctx.path.source)
              else
                return nil
              end
            elseif (true and (case_17_ == "lua")) then
              local _0 = case_16_
              local case_24_ = vim.fs.relpath(ctx.path.dest, path)
              if (nil ~= case_24_) then
                local rel_path = case_24_
                local renamed = string.gsub(string.gsub(rel_path, "^lua/", "fnl/"), "%.lua$", ".fnl")
                return vim.fs.joinpath(ctx.path.source, renamed)
              elseif (case_24_ == nil) then
                return nil, string.format("%s not under context destination %s", path, ctx.path.dest)
              else
                return nil
              end
            elseif (true and (nil ~= case_17_)) then
              local _0 = case_16_
              local ext0 = case_17_
              return nil, string.format("Unsupported extension %s, must be .fnl, .fnlm and .lua", ext0)
            else
              local _0 = case_16_
              return nil, string.format("Could not locate %s, perhaps its a directory or does not exist?", path)
            end
          end
        else
          local _0 = what
          return nil, string.format("Must give string to locate, got type %s ", type(what))
        end
      end
    end
    return _11_
  end
end
local function bind_metadata(ctx)
  if ((_G.type(ctx) == "table") and (ctx.kind == "api")) then
    local function _29_()
      return {kind = "api"}
    end
    return _29_
  else
    local _ = ctx
    local function _30_()
      return {target = ctx.target, kind = ctx.kind, source = ctx.path.source, destination = ctx.path.dest}
    end
    return _30_
  end
end
local function bind_context(ctx)
  local base = {compile = bind_compile(ctx), eval = bind_eval(ctx), sync = bind_sync(ctx), metadata = bind_metadata(ctx), locate = bind_locate(ctx)}
  if ctx.transform then
    local function _32_(source, _3ffilename)
      if (nil == source) then
        _G.error("Missing argument source on fnl/hotpot/api.fnl:87", 2)
      else
      end
      return ctx.transform(source, (_3ffilename or "--hotpot-api-transform"))
    end
    base.transform = _32_
  else
  end
  return base
end
M.context = function(_3ftarget)
  if (_3ftarget == nil) then
    return bind_context(R.Context.new())
  elseif ((_G.type(_3ftarget) == "table") and (_3ftarget.__type == "context")) then
    local internal = _3ftarget
    return bind_context(internal)
  else
    local and_35_ = (nil ~= _3ftarget)
    if and_35_ then
      local path = _3ftarget
      and_35_ = ("string" == type(path))
    end
    if and_35_ then
      local path = _3ftarget
      local case_37_, case_38_ = R.Context.nearest(path)
      if (nil ~= case_37_) then
        local root = case_37_
        local case_39_, case_40_ = pcall(R.Context.new, root)
        if ((case_39_ == true) and (nil ~= case_40_)) then
          local ctx = case_40_
          return bind_context(ctx)
        elseif ((case_39_ == false) and (nil ~= case_40_)) then
          local err = case_40_
          return nil, err
        else
          return nil
        end
      elseif ((case_37_ == nil) and (nil ~= case_38_)) then
        local err = case_38_
        return nil, err
      else
        return nil
      end
    elseif (nil ~= _3ftarget) then
      local other = _3ftarget
      return nil, string.format("api.context: bad argument type %s", type(other))
    else
      return nil
    end
  end
end
return M