-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("hotpot.util")
local R = _local_1_.R
local M, m = {}, {}
local function bind_compile(ctx)
  local function _2_(source, _3foptions)
    if (nil == source) then
      _G.error("Missing argument source on fnl/hotpot/api.fnl:5", 2)
    else
    end
    return pcall(R.context["compile-string"], ctx, source, vim.tbl_extend("force", (_3foptions or {}), {filename = "--hotpot-api-compile"}))
  end
  return _2_
end
local function bind_eval(ctx)
  local function _4_(source, _3foptions)
    if (nil == source) then
      _G.error("Missing argument source on fnl/hotpot/api.fnl:13", 2)
    else
    end
    return pcall(R.context["eval-string"], ctx, source, vim.tbl_extend("force", (_3foptions or {}), {filename = "--hotpot-api-eval"}))
  end
  return _4_
end
local function bind_sync(ctx)
  if ((_G.type(ctx) == "table") and (ctx.kind == "api")) then
    return nil
  else
    local _ = ctx
    local function _6_(_3foptions)
      return pcall(R.context.sync, ctx, _3foptions)
    end
    return _6_
  end
end
local function bind_locate(ctx)
  if ((_G.type(ctx) == "table") and (ctx.kind == "api")) then
    return nil
  else
    local _ = ctx
    local function _8_(what)
      if (nil == what) then
        _G.error("Missing argument what on fnl/hotpot/api.fnl:30", 2)
      else
      end
      if (what == "source") then
        return ctx.path.source
      elseif (what == "destination") then
        return ctx.path.dest
      else
        local and_10_ = (nil ~= what)
        if and_10_ then
          local path = what
          and_10_ = ("string" == type(path))
        end
        if and_10_ then
          local path = what
          local real_path = (vim.uv.fs_realpath(path) or path)
          local _let_12_ = R.const
          local NVIM_CONFIG_ROOT = _let_12_.NVIM_CONFIG_ROOT
          local init_fnl = vim.fs.joinpath(NVIM_CONFIG_ROOT, "init.fnl")
          local init_lua = vim.fs.joinpath(NVIM_CONFIG_ROOT, "init.lua")
          local ext = string.match(real_path, "%.([^%.]+)$")
          local case_13_, case_14_ = real_path, ext
          local and_15_ = (case_13_ == init_fnl)
          if and_15_ then
            and_15_ = _
          end
          if and_15_ then
            return init_lua
          else
            local and_17_ = (case_13_ == init_lua)
            if and_17_ then
              and_17_ = _
            end
            if and_17_ then
              return init_fnl
            elseif (true and (case_14_ == "fnlm")) then
              local _0 = case_13_
              return real_path
            elseif (true and (case_14_ == "fnl")) then
              local _0 = case_13_
              local case_19_ = vim.fs.relpath(ctx.path.source, path)
              if (nil ~= case_19_) then
                local rel_path = case_19_
                local renamed = string.gsub(string.gsub(rel_path, "^fnl/", "lua/"), "%.fnl$", ".lua")
                return vim.fs.joinpath(ctx.path.dest, renamed)
              elseif (case_19_ == nil) then
                return nil, string.format("%s not under context source %s", path, ctx.path.source)
              else
                return nil
              end
            elseif (true and (case_14_ == "lua")) then
              local _0 = case_13_
              local case_21_ = vim.fs.relpath(ctx.path.dest, path)
              if (nil ~= case_21_) then
                local rel_path = case_21_
                local renamed = string.gsub(string.gsub(rel_path, "^lua/", "fnl/"), "%.lua$", ".fnl")
                return vim.fs.joinpath(ctx.path.source, renamed)
              elseif (case_21_ == nil) then
                return nil, string.format("%s not under context destination %s", path, ctx.path.dest)
              else
                return nil
              end
            elseif (true and (nil ~= case_14_)) then
              local _0 = case_13_
              local ext0 = case_14_
              return nil, string.format("Unsupported extension %s, must be .fnl, .fnlm and .lua", ext0)
            else
              local _0 = case_13_
              return nil, string.format("Could not locate %s, perhaps its a directory or does not exist?", path)
            end
          end
        else
          local _0 = what
          return nil, string.format("Must give string to locate, got type %s ", type(what))
        end
      end
    end
    return _8_
  end
end
local function bind_context(ctx)
  local base = {compile = bind_compile(ctx), eval = bind_eval(ctx), sync = bind_sync(ctx), locate = bind_locate(ctx)}
  if ctx.transform then
    local function _26_(source, _3ffilename)
      if (nil == source) then
        _G.error("Missing argument source on fnl/hotpot/api.fnl:73", 2)
      else
      end
      return ctx.transform(source, (_3ffilename or "--hotpot-api-transform"))
    end
    base.transform = _26_
  else
  end
  return base
end
M.context = function(_3fpath)
  if (_3fpath == nil) then
    return bind_context(R.Context.new())
  elseif (nil ~= _3fpath) then
    local path = _3fpath
    local case_29_, case_30_ = R.Context.nearest(path)
    if (nil ~= case_29_) then
      local root = case_29_
      local case_31_, case_32_ = pcall(R.Context.new, root)
      if ((case_31_ == true) and (nil ~= case_32_)) then
        local ctx = case_32_
        return bind_context(ctx)
      elseif ((case_31_ == false) and (nil ~= case_32_)) then
        local err = case_32_
        return nil, err
      else
        return nil
      end
    elseif ((case_29_ == nil) and (nil ~= case_30_)) then
      local err = case_30_
      return nil, err
    else
      return nil
    end
  else
    return nil
  end
end
return M