-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("hotpot.util")
local R = _local_1_.R
local notify_error = _local_1_["notify-error"]
local M, m = {}, {}
local function silly_lsp_notification(buf, ctx, report)
  local client_id = R.lsp["start-lsp"]({root = ctx.path.source})
  return R.lsp["emit-report"](client_id, report)
end
local function buf_write_post_callback(event)
  local Context = R.Context
  local path = event.match
  local buf = event.buf
  do
    local case_2_ = Context.nearest(path)
    if (nil ~= case_2_) then
      local root = case_2_
      local function _3_(...)
        local case_4_, case_5_ = ...
        if ((case_4_ == true) and (nil ~= case_5_)) then
          local ctx = case_5_
          local function _6_(...)
            local case_7_, case_8_ = ...
            if ((case_7_ == true) and (nil ~= case_8_)) then
              local report = case_8_
              return silly_lsp_notification(buf, ctx, report)
            elseif ((case_7_ == false) and (nil ~= case_8_)) then
              local err = case_8_
              return notify_error(err)
            else
              return nil
            end
          end
          return _6_(pcall(Context.sync, ctx))
        elseif ((case_4_ == false) and (nil ~= case_5_)) then
          local err = case_5_
          return notify_error(err)
        else
          return nil
        end
      end
      _3_(pcall(Context.new, root))
    elseif (case_2_ == nil) then
    else
    end
  end
  return nil
end
local _2aaugroup_id_2a = nil
M.enable = function()
  if not _2aaugroup_id_2a then
    local augroup_id = vim.api.nvim_create_augroup("hotpot-fnl-ft", {clear = true})
    _2aaugroup_id_2a = augroup_id
    return vim.api.nvim_create_autocmd({"BufWritePost"}, {pattern = {"*.fnl", "*.fnlm"}, group = augroup_id, callback = buf_write_post_callback})
  else
    return nil
  end
end
M.disable = function()
  if _2aaugroup_id_2a then
    vim.api.nvim_del_augroup_by_id(_2aaugroup_id_2a)
    _2aaugroup_id_2a = nil
    return nil
  else
    return nil
  end
end
M["enabled?"] = function()
  return (nil ~= _2aaugroup_id_2a)
end
return M