-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _1_
do
  local path = vim.fn.stdpath("config")
  local case_2_ = vim.uv.fs_realpath(vim.fs.normalize(path))
  if (nil ~= case_2_) then
    local real_path = case_2_
    _1_ = real_path
  elseif (case_2_ == nil) then
    _1_ = path
  else
    _1_ = nil
  end
end
return {HOTPOT_CONFIG_CACHE_ROOT = vim.fs.normalize(vim.fs.joinpath(vim.fn.stdpath("data"), "site", "pack", "hotpot", "opt", "hotpot-config-cache")), HOTPOT_FENNEL_UPDATE_ROOT = vim.fs.normalize(vim.fs.joinpath(vim.fn.stdpath("data"), "site", "pack", "hotpot", "opt", "hotpot-fennel-update")), HOTPOT_FENNEL_UPDATE_LUA_ROOT = vim.fs.normalize(vim.fs.joinpath(vim.fn.stdpath("data"), "site", "pack", "hotpot", "opt", "hotpot-fennel-update", "lua", "hotpot", "fennel-update")), NVIM_CONFIG_ROOT = _1_}