-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("hotpot.util")
local R = _local_1_.R
local _local_2_ = require("hotpot.util")
local R0 = _local_2_.R
local notify_error = _local_2_["notify-error"]
local notify_warn = _local_2_["notify-warn"]
local notify_info = _local_2_["notify-info"]
local M, m = {}, {}
local _2ahotpot_ownership_marker_2a = "-- @generated by hotpot.nvim"
local _2ahotpot_ownership_marker_length_2a = #_2ahotpot_ownership_marker_2a
local function mark_ownership(source)
  return (string.format("%s using fennel %s, edits to this file may be lost\n", _2ahotpot_ownership_marker_2a, R0.fennel.version) .. source)
end
local function hotpot_generated_3f(file)
  local fd = io.open(file, "r")
  local function close_handlers_13_(ok_14_, ...)
    fd:close()
    if ok_14_ then
      return ...
    else
      return error(..., 0)
    end
  end
  local function _4_()
    local header = string.sub((fd:read(256) or ""), 1, #_2ahotpot_ownership_marker_2a)
    return (header == _2ahotpot_ownership_marker_2a)
  end
  local _6_
  do
    local t_5_ = _G
    if (nil ~= t_5_) then
      t_5_ = t_5_.package
    else
    end
    if (nil ~= t_5_) then
      t_5_ = t_5_.loaded
    else
    end
    if (nil ~= t_5_) then
      t_5_ = t_5_.fennel
    else
    end
    _6_ = t_5_
  end
  local or_10_ = _6_ or _G.debug
  if not or_10_ then
    local function _11_()
      return ""
    end
    or_10_ = {traceback = _11_}
  end
  return close_handlers_13_(_G.xpcall(_4_, or_10_.traceback))
end
local function validate_user_spec(user_spec, path)
  local function assert_value(key, want, has)
    assert((want == has), string.format("%s `%s` must be `%s`", path, key, want))
    return nil
  end
  local function assert_type(key, want, value)
    assert((want == type(value)), string.format("%s `%s` must have type `%s`", path, key, want))
    return nil
  end
  assert(("table" == type(user_spec)), string.format("%s must return a table", path))
  local known_keys
  local function _12_(_241)
    return assert_value("schema", "hotpot/2", _241)
  end
  local function _13_(_241)
    assert((("cache" == _241) or ("colocate" == _241)), string.format("%s `target` must be `cache` or `colocate`", path))
    return nil
  end
  local function _14_(_241)
    return assert_type("atomic?", "boolean", _241)
  end
  local function _15_(_241)
    return assert_type("verbose?", "boolean", _241)
  end
  local function _16_(_241)
    assert_type("ignore", "table", _241)
    for _, v in ipairs(_241) do
      assert_type("ignore.values", "string", v)
    end
    return nil
  end
  local function _17_(_241)
    return assert_type("transform", "function", _241)
  end
  local function _18_(_241)
    return assert_type("compiler", "table", _241)
  end
  known_keys = {schema = _12_, target = _13_, ["atomic?"] = _14_, ["verbose?"] = _15_, ignore = _16_, transform = _17_, compiler = _18_}
  local unknown_keys
  do
    local tbl_26_ = {}
    local i_27_ = 0
    for key, value in pairs(user_spec) do
      local val_28_
      do
        local case_19_ = known_keys[key]
        if (nil ~= case_19_) then
          local func = case_19_
          val_28_ = func(value)
        elseif (case_19_ == nil) then
          val_28_ = key
        else
          val_28_ = nil
        end
      end
      if (nil ~= val_28_) then
        i_27_ = (i_27_ + 1)
        tbl_26_[i_27_] = val_28_
      else
      end
    end
    unknown_keys = tbl_26_
  end
  assert((0 == #unknown_keys), string.format("\n.%s had invalid keys: %s.\nMust be one of: %s.", path, table.concat(unknown_keys, ", "), table.concat(vim.tbl_keys(known_keys), ", ")))
  return true
end
local function base_spec()
  local _22_
  do
    local tbl_26_ = {}
    local i_27_ = 0
    for k, _ in pairs(_G) do
      local val_28_ = k
      if (nil ~= val_28_) then
        i_27_ = (i_27_ + 1)
        tbl_26_[i_27_] = val_28_
      else
      end
    end
    _22_ = tbl_26_
  end
  return {schema = "hotpot/2", ["atomic?"] = true, ignore = {}, transform = nil, compiler = {allowedGlobals = _22_, ["error-pinpoint"] = false}, ["verbose?"] = false}
end
local function is_init_lua_special_case_3f(ctx, fnl_rel)
  if (nil == fnl_rel) then
    _G.error("Missing argument fnl-rel on fnl/hotpot/context.fnl:77", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:77", 2)
  else
  end
  local case_26_, case_27_, case_28_ = ctx.kind, ctx.target, fnl_rel
  if ((case_26_ == "config") and (case_27_ == "cache") and (case_28_ == "init.fnl")) then
    return true
  else
    local _ = case_26_
    return false
  end
end
local function default_config_spec()
  return vim.tbl_extend("force", base_spec(), {target = "cache"})
end
local function default_api_spec()
  return base_spec()
end
local function err_msg_unable_to_load(path, m0)
  return string.format("Unable to load %s: %s", path, m0)
end
local function load_spec_file(path)
  if (nil == path) then
    _G.error("Missing argument path on fnl/hotpot/context.fnl:94", 2)
  else
  end
  assert(vim.uv.fs_stat(path), err_msg_unable_to_load(path, "does not exist"))
  local fennel = R0.fennel
  local content
  do
    local case_31_ = vim.secure.read(path)
    if (nil ~= case_31_) then
      local content0 = case_31_
      content = content0
    elseif (case_31_ == nil) then
      content = error(string.format("Unable to continue with untrusted file: %s", path))
    else
      content = nil
    end
  end
  local _let_33_ = m["make-fennel-path-modifiers"]({path = {source = vim.fs.dirname(path)}}, fennel)
  local update_fennel_path = _let_33_["update-fennel-path"]
  local restore_fennel_path = _let_33_["restore-fennel-path"]
  local _ = update_fennel_path()
  local ok_3f, def = pcall(fennel.eval, content)
  local _0 = restore_fennel_path()
  assert(ok_3f, err_msg_unable_to_load(path, def))
  validate_user_spec(def, path)
  return def
end
local function user_spec__3econtext(user_spec, meta)
  if (nil == meta) then
    _G.error("Missing argument meta on fnl/hotpot/context.fnl:112", 2)
  else
  end
  if (nil == user_spec) then
    _G.error("Missing argument user-spec on fnl/hotpot/context.fnl:112", 2)
  else
  end
  local source = meta.source
  local kind = meta.kind
  local _let_36_ = R0.const
  local HOTPOT_CONFIG_CACHE_ROOT = _let_36_.HOTPOT_CONFIG_CACHE_ROOT
  local path
  if ((_G.type(meta) == "table") and (meta.kind == "api")) then
    path = {}
  elseif ((_G.type(meta) == "table") and (meta.root == nil)) then
    path = error(err_msg_unable_to_load("unknown", "internal error: did not provide root directory to user-spec->context"))
  elseif ((_G.type(meta) == "table") and (meta.kind == "config") and (nil ~= meta.root)) then
    local root = meta.root
    if ((_G.type(user_spec) == "table") and (user_spec.target == "cache")) then
      path = {source = root, dest = HOTPOT_CONFIG_CACHE_ROOT}
    elseif ((_G.type(user_spec) == "table") and (user_spec.target == "colocate")) then
      path = {source = root, dest = root}
    else
      path = nil
    end
  elseif ((_G.type(meta) == "table") and (meta.kind == "plugin") and (nil ~= meta.root)) then
    local root = meta.root
    if ((_G.type(user_spec) == "table") and (user_spec.target == "colocate")) then
      path = {source = root, dest = root}
    elseif ((_G.type(user_spec) == "table") and (user_spec.target == "cache")) then
      path = error(err_msg_unable_to_load(root, "non-config directories may only use target: :colocate"))
    else
      path = nil
    end
  else
    local _ = meta
    path = error(err_msg_unable_to_load("unknown", "internal error: spec meta missing kind"))
  end
  local ctx = base_spec()
  local user_compiler_options = user_spec.compiler
  local _
  user_spec.compiler = nil
  _ = nil
  local ctx0 = vim.tbl_extend("force", base_spec(), user_spec, {__type = "context", kind = kind, path = path, source = (source or "in-memory")})
  if user_compiler_options then
    ctx0.compiler = vim.tbl_extend("force", ctx0.compiler, user_compiler_options)
  else
  end
  do
    local tbl_26_ = {}
    local i_27_ = 0
    for _0, glob in ipairs(ctx0.ignore) do
      local val_28_ = vim.glob.to_lpeg(glob)
      if (nil ~= val_28_) then
        i_27_ = (i_27_ + 1)
        tbl_26_[i_27_] = val_28_
      else
      end
    end
    ctx0.ignore = tbl_26_
  end
  if ctx0.transform then
    assert(("function" == type(ctx0.transform)), string.format("%s `transform` not a function", ctx0.source))
  else
  end
  return ctx0
end
m["find-files"] = function(root, extension_pattern, ignore)
  if (nil == ignore) then
    _G.error("Missing argument ignore on fnl/hotpot/context.fnl:164", 2)
  else
  end
  if (nil == extension_pattern) then
    _G.error("Missing argument extension-pattern on fnl/hotpot/context.fnl:164", 2)
  else
  end
  if (nil == root) then
    _G.error("Missing argument root on fnl/hotpot/context.fnl:164", 2)
  else
  end
  local function _46_(name, dir)
    local path = vim.fs.relpath(root, vim.fs.joinpath(dir, name), {})
    local and_47_ = (".hotpot.fnl" ~= name) and name:match(extension_pattern)
    if and_47_ then
      local ok_3f = true
      for _, rule in ipairs(ignore) do
        if not ok_3f then break end
        ok_3f = not rule:match(path)
      end
      and_47_ = ok_3f
    end
    return and_47_
  end
  return vim.fs.find(_46_, {limit = math.huge, type = "file", path = root})
end
m["find-source-files"] = function(ctx)
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:179", 2)
  else
  end
  local _let_49_ = ctx.path
  local source = _let_49_.source
  local dest = _let_49_.dest
  local ignore = ctx.ignore
  local files = m["find-files"](source, "%.fnlm?$", ignore)
  local list = {fnl = {}, fnlm = {}}
  for _, fnl_abs in ipairs(files) do
    local ext = fnl_abs:match("%.(fnlm?)$")
    local fnl_rel = vim.fs.relpath(source, fnl_abs, {})
    local lua_rel, lua_abs
    if ("fnl" == ext) then
      if is_init_lua_special_case_3f(ctx, fnl_rel) then
        local lua_rel0 = string.gsub(fnl_rel, "%.fnl$", ".lua")
        local lua_abs0 = vim.fs.joinpath(source, lua_rel0)
        lua_rel, lua_abs = lua_rel0, lua_abs0
      else
        local lua_rel0 = string.gsub(string.gsub(fnl_rel, "^fnl/", "lua/"), "%.fnl$", ".lua")
        local lua_abs0 = vim.fs.joinpath(dest, lua_rel0)
        lua_rel, lua_abs = lua_rel0, lua_abs0
      end
    else
      lua_rel, lua_abs = nil
    end
    table.insert(list[ext], {["fnl-rel"] = fnl_rel, ["fnl-abs"] = fnl_abs, ["lua-rel"] = lua_rel, ["lua-abs"] = lua_abs})
    list = list
  end
  return list
end
m["find-orphaned-files"] = function(ctx, source_files)
  if (nil == source_files) then
    _G.error("Missing argument source-files on fnl/hotpot/context.fnl:204", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:204", 2)
  else
  end
  local _let_54_ = ctx.path
  local dest = _let_54_.dest
  local ignore = ctx.ignore
  local known_lua_files
  do
    local tbl_21_ = {}
    for _, _55_ in ipairs(source_files.fnl) do
      local lua_abs = _55_["lua-abs"]
      local k_22_, v_23_ = lua_abs, true
      if ((k_22_ ~= nil) and (v_23_ ~= nil)) then
        tbl_21_[k_22_] = v_23_
      else
      end
    end
    known_lua_files = tbl_21_
  end
  local lua_files_in_dest = m["find-files"](dest, "%.lua$", ignore)
  local orphans
  do
    local tbl_26_ = {}
    local i_27_ = 0
    for _, path in ipairs(lua_files_in_dest) do
      local val_28_
      do
        local case_57_ = known_lua_files[path]
        if (case_57_ == nil) then
          local lua_abs = path
          local lua_rel = vim.fs.relpath(dest, lua_abs)
          val_28_ = {["lua-abs"] = lua_abs, ["lua-rel"] = lua_rel}
        else
          val_28_ = nil
        end
      end
      if (nil ~= val_28_) then
        i_27_ = (i_27_ + 1)
        tbl_26_[i_27_] = val_28_
      else
      end
    end
    orphans = tbl_26_
  end
  return orphans
end
m["filter-stale-source-files"] = function(files)
  if (nil == files) then
    _G.error("Missing argument files on fnl/hotpot/context.fnl:217", 2)
  else
  end
  local fnl = files.fnl
  local fnlm = files.fnlm
  local _let_61_ = R0.util
  local file_mtime = _let_61_["file-mtime"]
  local fnlm_mtime
  do
    local newest_mtime
    local function _62_()
      return false
    end
    newest_mtime = {sec = 0, nsec = 0, ["after?"] = _62_}
    for _, _63_ in ipairs(fnlm) do
      local fnl_abs = _63_["fnl-abs"]
      local this_mtime = file_mtime(fnl_abs)
      if this_mtime["after?"](this_mtime, newest_mtime) then
        newest_mtime = this_mtime
      else
        newest_mtime = newest_mtime
      end
    end
    fnlm_mtime = newest_mtime
  end
  local needs_compiling
  do
    local tbl_26_ = {}
    local i_27_ = 0
    for _, _65_ in ipairs(fnl) do
      local fnl_abs = _65_["fnl-abs"]
      local lua_abs = _65_["lua-abs"]
      local file = _65_
      local val_28_
      do
        local lua_mtime = file_mtime(lua_abs)
        local fnl_mtime = file_mtime(fnl_abs)
        if (not lua_mtime or fnl_mtime["after?"](fnl_mtime, lua_mtime) or fnlm_mtime["after?"](fnlm_mtime, lua_mtime)) then
          val_28_ = file
        else
          val_28_ = nil
        end
      end
      if (nil ~= val_28_) then
        i_27_ = (i_27_ + 1)
        tbl_26_[i_27_] = val_28_
      else
      end
    end
    needs_compiling = tbl_26_
  end
  return needs_compiling
end
m["apply-transform"] = function(ctx, source, path)
  if (nil == path) then
    _G.error("Missing argument path on fnl/hotpot/context.fnl:238", 2)
  else
  end
  if (nil == source) then
    _G.error("Missing argument source on fnl/hotpot/context.fnl:238", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:238", 2)
  else
  end
  local case_71_ = ctx.transform
  if (nil ~= case_71_) then
    local transform = case_71_
    local new_src = transform(source, path)
    local case_72_ = type(new_src)
    if (case_72_ == "string") then
      return new_src
    elseif (nil ~= case_72_) then
      local other = case_72_
      return error(string.format("%s `transform` returned %s instead of string", ctx.source, other))
    else
      return nil
    end
  else
    local _ = case_71_
    return source
  end
end
local init_lua_choice = nil
m["sync-plan-compile"] = function(ctx, source_files, force_3f)
  if (nil == force_3f) then
    _G.error("Missing argument force? on fnl/hotpot/context.fnl:247", 2)
  else
  end
  if (nil == source_files) then
    _G.error("Missing argument source-files on fnl/hotpot/context.fnl:247", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:247", 2)
  else
  end
  local fnl_source_files
  if force_3f then
    fnl_source_files = source_files.fnl
  else
    fnl_source_files = m["filter-stale-source-files"](source_files)
  end
  local init_lua_index
  do
    local found = nil
    for i, _79_ in ipairs(fnl_source_files) do
      local fnl_rel = _79_["fnl-rel"]
      if found then break end
      if is_init_lua_special_case_3f(ctx, fnl_rel) then
        found = i
      else
        found = nil
      end
    end
    init_lua_index = found
  end
  if init_lua_index then
    if not init_lua_choice then
      local ui_select_sync = R0.ui["ui-select-sync"]
      local yes_once = "Overwite init.lua with init.fnl (ask again next time)"
      local no_once = "Leave init.lua as it is (ask again next time)"
      local yes_always = "Overwite init.lua with init.fnl (always for this session)"
      local no_always = "Leave init.lua as it is (always for this session)"
      local prompt = string.format("Overwrite any existing `%s/init.lua` with output from `%s/init.fnl?", ctx.path.source, ctx.path.source)
      local callback
      local function _81_(choice)
        local case_82_, case_83_ = choice
        if (case_82_ == yes_once) then
          return "yes-once"
        elseif (case_82_ == no_once) then
          return "no-once"
        elseif (case_82_ == yes_always) then
          return "yes-always"
        elseif (case_82_ == no_always) then
          return "no-always"
        else
          local _ = case_82_
          return "no-once"
        end
      end
      callback = _81_
      init_lua_choice = ui_select_sync({yes_once, no_once, yes_always, no_always}, {prompt = prompt}, callback)
    else
    end
    if (init_lua_choice == "yes-once") then
      init_lua_choice = nil
    elseif (init_lua_choice == "yes-always") then
    elseif (init_lua_choice == "no-once") then
      table.remove(fnl_source_files, init_lua_index)
      init_lua_choice = nil
    elseif (init_lua_choice == "no-always") then
      table.remove(fnl_source_files, init_lua_index)
    else
    end
  else
  end
  return fnl_source_files
end
m["sync-compile"] = function(ctx, fnl_files, _3fextra_options)
  if (nil == fnl_files) then
    _G.error("Missing argument fnl-files on fnl/hotpot/context.fnl:284", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:284", 2)
  else
  end
  for key, _ in pairs(R0.fennel["macro-loaded"]) do
    R0.fennel["macro-loaded"][key] = nil
  end
  local results = {ok = {}, errors = {}}
  for _, _90_ in ipairs(fnl_files) do
    local fnl_abs = _90_["fnl-abs"]
    local fnl_rel = _90_["fnl-rel"]
    local lua_abs = _90_["lua-abs"]
    local lua_rel = _90_["lua-rel"]
    local fnl_source = R0.util["file-read"](fnl_abs)
    local fnl_source0 = m["apply-transform"](ctx, fnl_source, fnl_rel)
    local extra_options = vim.tbl_extend("force", (_3fextra_options or {}), {filename = fnl_rel})
    local time_start = vim.uv.hrtime()
    local ok_3f, result = pcall(M["compile-string"], ctx, fnl_source0, extra_options)
    local time_stop = vim.uv.hrtime()
    local duration_ms = ((time_stop - time_start) / 1000000)
    local case_91_, case_92_ = ok_3f, result
    if ((case_91_ == true) and (nil ~= case_92_)) then
      local lua_source = case_92_
      table.insert(results.ok, {["fnl-abs"] = fnl_abs, ["fnl-rel"] = fnl_rel, ["lua-abs"] = lua_abs, ["lua-rel"] = lua_rel, ["duration-ms"] = duration_ms, source = mark_ownership(lua_source)})
      results = results
    elseif ((case_91_ == false) and (nil ~= case_92_)) then
      local err = case_92_
      table.insert(results.errors, {["fnl-abs"] = fnl_abs, ["fnl-rel"] = fnl_rel, ["lua-abs"] = lua_abs, ["lua-rel"] = lua_rel, ["duration-ms"] = duration_ms, error = err})
      results = results
    else
      results = nil
    end
  end
  return results
end
m["sync-write"] = function(ctx, output_files)
  if (nil == output_files) then
    _G.error("Missing argument output-files on fnl/hotpot/context.fnl:335", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:335", 2)
  else
  end
  for _, _96_ in ipairs(output_files) do
    local lua_abs = _96_["lua-abs"]
    local source = _96_.source
    vim.fn.mkdir(vim.fs.dirname(lua_abs), "p")
    R0.util["file-write"](lua_abs, source)
  end
  return nil
end
m["sync-plan-clean"] = function(ctx, source_files)
  if (nil == source_files) then
    _G.error("Missing argument source-files on fnl/hotpot/context.fnl:340", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:340", 2)
  else
  end
  local all_orphan_files = m["find-orphaned-files"](ctx, source_files)
  local owned_orphans, unowned_orphans
  do
    local owned, unowned = {}, {}
    for _, _99_ in ipairs(all_orphan_files) do
      local lua_abs = _99_["lua-abs"]
      local file = _99_
      if hotpot_generated_3f(lua_abs) then
        local _100_
        do
          table.insert(owned, file)
          _100_ = owned
        end
        owned, unowned = _100_, unowned
      else
        local function _101_()
          table.insert(unowned, file)
          return unowned
        end
        owned, unowned = owned, _101_()
      end
    end
    owned_orphans, unowned_orphans = owned, unowned
  end
  return {owned = owned_orphans, unowned = unowned_orphans}
end
m["sync-clean"] = function(ctx, orphan_files)
  if (nil == orphan_files) then
    _G.error("Missing argument orphan-files on fnl/hotpot/context.fnl:353", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:353", 2)
  else
  end
  for _, _105_ in ipairs(orphan_files) do
    local lua_abs = _105_["lua-abs"]
    vim.uv.fs_unlink(lua_abs)
  end
  return nil
end
m["sync-plan-confirm"] = function(ctx, compiled_files, orphan_files)
  if (nil == orphan_files) then
    _G.error("Missing argument orphan-files on fnl/hotpot/context.fnl:357", 2)
  else
  end
  if (nil == compiled_files) then
    _G.error("Missing argument compiled-files on fnl/hotpot/context.fnl:357", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:357", 2)
  else
  end
  if ((_G.type(ctx) == "table") and (ctx.kind == "api")) then
    return error("unable to sync-plan-confirm in context.kind == api")
  elseif ((_G.type(ctx) == "table") and (ctx.target == "cache")) then
    return {write = compiled_files, clean = {unowned = orphan_files.unowned, owned = orphan_files.owned}}
  elseif ((_G.type(ctx) == "table") and (ctx.target == "colocate")) then
    if ((_G.type(orphan_files) == "table") and ((_G.type(orphan_files.unowned) == "table") and (orphan_files.unowned[1] == nil))) then
      return {write = compiled_files, clean = {unowned = orphan_files.unowned, owned = orphan_files.owned}}
    elseif ((_G.type(orphan_files) == "table") and (nil ~= orphan_files.unowned)) then
      local unowned = orphan_files.unowned
      local ui_select_sync = R0.ui["ui-select-sync"]
      local show_file_prompt
      local function _109_()
        local prompt = "Select any file or cancel to return to previous menu."
        local choices
        do
          local tbl_26_ = {}
          local i_27_ = 0
          for _, _110_ in ipairs(unowned) do
            local lua_abs = _110_["lua-abs"]
            local val_28_ = lua_abs
            if (nil ~= val_28_) then
              i_27_ = (i_27_ + 1)
              tbl_26_[i_27_] = val_28_
            else
            end
          end
          choices = tbl_26_
        end
        local callback
        local function _112_()
          return nil
        end
        callback = _112_
        return ui_select_sync(choices, {prompt = prompt}, callback)
      end
      show_file_prompt = _109_
      local show_confirm_prompt
      local function show_confirm_prompt0()
        local choices = {string.format("View list of %d orphaned files then return to this prompt", #unowned), "Ok: Remove orphaned files and compile as normal", "Safe: Keep orphaned files but compile as normal", "Cancel: Do not remove files or compile"}
        local prompt = string.format("Found %d un-ignored lua files with no fnl source, delete all?", #unowned)
        local callback
        local function _113_(choice_word, choice_int)
          if (choice_int == 1) then
            return nil
          elseif (choice_int == 2) then
            return {write = compiled_files, clean = {unowned = orphan_files.unowned, owned = orphan_files.owned}}
          elseif (choice_int == 3) then
            return {write = compiled_files, clean = {unowned = {}, owned = orphan_files.owned}}
          elseif (choice_int == 4) then
            return {write = {}, clean = {unowned = {}, owned = {}}}
          elseif (choice_int == nil) then
            return {write = {}, clean = {unowned = {}, owned = {}}}
          else
            local _ = choice_int
            return error("bad choice int for show-prompt-confirm")
          end
        end
        callback = _113_
        local case_115_ = ui_select_sync(choices, {prompt = prompt}, callback)
        if (nil ~= case_115_) then
          local choice = case_115_
          return choice
        elseif (case_115_ == nil) then
          show_file_prompt()
          return show_confirm_prompt0()
        else
          return nil
        end
      end
      show_confirm_prompt = show_confirm_prompt0
      return show_confirm_prompt()
    else
      return nil
    end
  else
    local _ = ctx
    return error(string.format("internal error: unknown ctx %s", vim.inspect(ctx)))
  end
end
m["make-fennel-path-modifiers"] = function(ctx, fennel)
  if (nil == fennel) then
    _G.error("Missing argument fennel on fnl/hotpot/context.fnl:411", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:411", 2)
  else
  end
  if ("api" == ctx.kind) then
    local function _121_()
      return nil
    end
    local function _122_()
      return nil
    end
    return {["update-fennel-path"] = _121_, ["restore-fennel-path"] = _122_}
  else
    local directory_prefix = ctx.path.source
    local _
    if not directory_prefix then
      _ = error(vim.inspect(ctx))
    else
      _ = nil
    end
    local old_paths = {path = fennel.path, ["macro-path"] = fennel["macro-path"]}
    local new_paths = {path = table.concat({(directory_prefix .. "/fnl/?.fnl"), (directory_prefix .. "/fnl/?/init.fnl"), (directory_prefix .. "/?.fnl"), (directory_prefix .. "/?/init.fnl"), old_paths.path}, ";"), ["macro-path"] = table.concat({(directory_prefix .. "/fnl/?.fnlm"), (directory_prefix .. "/fnl/?/init.fnlm"), (directory_prefix .. "/fnl/?.fnl"), (directory_prefix .. "/fnl/?/init-macros.fnl"), (directory_prefix .. "/fnl/?/init.fnl"), (directory_prefix .. "/?.fnlm"), (directory_prefix .. "/?/init.fnlm"), (directory_prefix .. "/?.fnl"), (directory_prefix .. "/?/init-macros.fnl"), (directory_prefix .. "/?/init.fnl"), old_paths["macro-path"]}, ";")}
    local function _124_()
      fennel.path = new_paths.path
      fennel["macro-path"] = new_paths["macro-path"]
      return nil
    end
    local function _125_()
      fennel.path = old_paths.path
      fennel["macro-path"] = old_paths["macro-path"]
      return nil
    end
    return {["update-fennel-path"] = _124_, ["restore-fennel-path"] = _125_}
  end
end
M.new = function(_3fdirectory)
  if (nil ~= _3fdirectory) then
    local directory = _3fdirectory
    local _let_127_ = R0.const
    local NVIM_CONFIG_ROOT = _let_127_.NVIM_CONFIG_ROOT
    local dot_hotpot_path = vim.fs.normalize(vim.fs.joinpath(directory, ".hotpot.fnl"))
    local dot_hotpot_exists_3f = (nil ~= vim.uv.fs_realpath(dot_hotpot_path))
    local real_directory = vim.uv.fs_realpath(vim.fs.normalize(directory))
    local is_config_root_3f
    if (nil ~= real_directory) then
      local any = real_directory
      is_config_root_3f = (real_directory == NVIM_CONFIG_ROOT)
    elseif (real_directory == nil) then
      is_config_root_3f = (directory == NVIM_CONFIG_ROOT)
    else
      is_config_root_3f = nil
    end
    local case_129_, case_130_ = dot_hotpot_exists_3f, is_config_root_3f
    if ((case_129_ == true) and (case_130_ == true)) then
      return user_spec__3econtext(load_spec_file(dot_hotpot_path), {root = NVIM_CONFIG_ROOT, kind = "config", source = dot_hotpot_path})
    elseif ((case_129_ == false) and (case_130_ == true)) then
      return user_spec__3econtext(default_config_spec(), {root = NVIM_CONFIG_ROOT, kind = "config"})
    elseif ((case_129_ == true) and (case_130_ == false)) then
      return user_spec__3econtext(load_spec_file(dot_hotpot_path), {root = real_directory, kind = "plugin", source = dot_hotpot_path})
    elseif ((case_129_ == false) and (case_130_ == false)) then
      return error(err_msg_unable_to_load(dot_hotpot_path, "does not exist"))
    else
      return nil
    end
  elseif (_3fdirectory == nil) then
    return user_spec__3econtext(default_api_spec(), {kind = "api"})
  else
    return nil
  end
end
M.nearest = function(starting_path)
  if (nil == starting_path) then
    _G.error("Missing argument starting-path on fnl/hotpot/context.fnl:517", 2)
  else
  end
  local case_134_ = vim.uv.fs_realpath(starting_path)
  if (nil ~= case_134_) then
    local real_starting_path = case_134_
    local inside_config_3f = (nil ~= vim.fs.relpath(R0.const.NVIM_CONFIG_ROOT, real_starting_path))
    local inside_cache_3f = (nil ~= vim.fs.relpath(R0.const.HOTPOT_CONFIG_CACHE_ROOT, real_starting_path))
    if (inside_config_3f or inside_cache_3f) then
      return R0.const.NVIM_CONFIG_ROOT
    else
      local case_135_ = vim.fs.root(real_starting_path, ".hotpot.fnl")
      if (case_135_ == nil) then
        return nil, string.format("Unable to find nearest context to '%s': no .hotpot.fnl in tree", starting_path)
      elseif (nil ~= case_135_) then
        local root = case_135_
        return root
      else
        return nil
      end
    end
  elseif (case_134_ == nil) then
    return nil, string.format("Unable to find nearest context to '%s': does not exist", starting_path)
  else
    return nil
  end
end
local function make_warn_impl(filename)
  if (nil == filename) then
    _G.error("Missing argument filename on fnl/hotpot/context.fnl:538", 2)
  else
  end
  local function _140_(warning)
    return notify_warn("Fennel compiler warning for %s: %s", filename, warning)
  end
  return _140_
end
M["compile-string"] = function(ctx, fnl_source, options)
  if (nil == options) then
    _G.error("Missing argument options on fnl/hotpot/context.fnl:542", 2)
  else
  end
  if (nil == fnl_source) then
    _G.error("Missing argument fnl-source on fnl/hotpot/context.fnl:542", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:542", 2)
  else
  end
  assert(options.filename, "tried to compile without filename")
  local fennel = R0.fennel
  local compiler_options = vim.tbl_extend("force", ctx.compiler, options, {filename = options.filename, warn = make_warn_impl(options.filename), ["error-pinpoint"] = false})
  local _let_144_ = m["make-fennel-path-modifiers"](ctx, fennel)
  local update_fennel_path = _let_144_["update-fennel-path"]
  local restore_fennel_path = _let_144_["restore-fennel-path"]
  local _ = update_fennel_path()
  local ok_3f, val = pcall(fennel["compile-string"], fnl_source, compiler_options)
  local _0 = restore_fennel_path()
  local case_145_, case_146_ = ok_3f, val
  if ((case_145_ == true) and (nil ~= case_146_)) then
    local src = case_146_
    return src
  elseif ((case_145_ == false) and (nil ~= case_146_)) then
    local err = case_146_
    return error(err)
  else
    return nil
  end
end
M["eval-string"] = function(ctx, fnl_source, options)
  if (nil == options) then
    _G.error("Missing argument options on fnl/hotpot/context.fnl:562", 2)
  else
  end
  if (nil == fnl_source) then
    _G.error("Missing argument fnl-source on fnl/hotpot/context.fnl:562", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:562", 2)
  else
  end
  local fennel = R0.fennel
  local _let_151_ = R0.util
  local pack = _let_151_.pack
  local compiler_options = vim.tbl_extend("force", ctx.compiler, options, {filename = options.filename, warn = make_warn_impl(options.filename), ["error-pinpoint"] = false})
  local _let_152_ = m["make-fennel-path-modifiers"](ctx, fennel)
  local update_fennel_path = _let_152_["update-fennel-path"]
  local restore_fennel_path = _let_152_["restore-fennel-path"]
  local _ = update_fennel_path()
  local returns = pack(pcall(fennel.eval, fnl_source, compiler_options))
  local _0 = restore_fennel_path()
  local case_153_ = returns[1]
  if (case_153_ == true) then
    return unpack(returns, 2, returns.n)
  elseif (case_153_ == false) then
    return error(returns[2])
  else
    return nil
  end
end
M.sync = function(ctx, _3foptions)
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/context.fnl:581", 2)
  else
  end
  local function option_if_set(key)
    local case_156_
    do
      local t_157_ = _3foptions
      if (nil ~= t_157_) then
        t_157_ = t_157_[key]
      else
      end
      case_156_ = t_157_
    end
    if (case_156_ == nil) then
      return ctx[key]
    elseif (nil ~= case_156_) then
      local val = case_156_
      return val
    else
      return nil
    end
  end
  local force_3f = (option_if_set("force?") or false)
  local atomic_3f = option_if_set("atomic?")
  local verbose_3f = option_if_set("verbose?")
  local extra_compiler_options
  local _161_
  do
    local t_160_ = _3foptions
    if (nil ~= t_160_) then
      t_160_ = t_160_.compiler
    else
    end
    _161_ = t_160_
  end
  extra_compiler_options = (_161_ or {})
  local source_files = m["find-source-files"](ctx)
  local stale_files = m["sync-plan-compile"](ctx, source_files, force_3f)
  local orphan_files = m["sync-plan-clean"](ctx, source_files)
  local time_start = vim.uv.hrtime()
  local _let_163_ = m["sync-compile"](ctx, stale_files, extra_compiler_options)
  local compile_oks = _let_163_.ok
  local compile_errors = _let_163_.errors
  local time_stop = vim.uv.hrtime()
  local total_duration_ms = ((time_stop - time_start) / 1000000)
  local has_errors_3f = (0 < #compile_errors)
  local printable_report = {}
  local data_report = {sources = source_files, compiled = {}, cleaned = {}, errors = compile_errors}
  local extend_report
  local function _164_(t, line_fn)
    local function _165_()
      local tbl_26_ = {}
      local i_27_ = 0
      for _, el in ipairs(t) do
        local val_28_ = line_fn(el)
        if (nil ~= val_28_) then
          i_27_ = (i_27_ + 1)
          tbl_26_[i_27_] = val_28_
        else
        end
      end
      return tbl_26_
    end
    return vim.list_extend(printable_report, _165_())
  end
  extend_report = _164_
  if (not has_errors_3f or not atomic_3f) then
    local _let_167_ = m["sync-plan-confirm"](ctx, compile_oks, orphan_files)
    local write = _let_167_.write
    local clean = _let_167_.clean
    do
      m["sync-write"](ctx, write)
      do
        local tbl_26_ = {}
        local i_27_ = 0
        for _, v in ipairs(write) do
          local val_28_
          do
            v["source"] = nil
            val_28_ = v
          end
          if (nil ~= val_28_) then
            i_27_ = (i_27_ + 1)
            tbl_26_[i_27_] = val_28_
          else
          end
        end
        data_report.compiled = tbl_26_
      end
      if ((0 < #write) and verbose_3f) then
        local function _170_(_169_)
          local fnl_abs = _169_["fnl-abs"]
          local lua_abs = _169_["lua-abs"]
          local duration_ms = _169_["duration-ms"]
          return {string.format("\226\152\145  %s (%.2fms)\n-> %s\n", fnl_abs, duration_ms, lua_abs), "DiagnosticOk"}
        end
        extend_report(write, _170_)
        local function _171_(_241)
          return _241
        end
        extend_report({{string.format("Duration: %.2fms\n", total_duration_ms), "DiagnosticInfo"}}, _171_)
      else
      end
    end
    local unowned = clean.unowned
    local owned = clean.owned
    m["sync-clean"](ctx, owned)
    m["sync-clean"](ctx, unowned)
    data_report.cleaned = clean
    if verbose_3f then
      local function _174_(_173_)
        local lua_abs = _173_["lua-abs"]
        return {string.format("rm %s\n", lua_abs), "DiagnosticInfo"}
      end
      extend_report(unowned, _174_)
      local function _176_(_175_)
        local lua_abs = _175_["lua-abs"]
        return {string.format("rm %s\n", lua_abs), "DiagnosticInfo"}
      end
      extend_report(owned, _176_)
    else
    end
  else
  end
  if has_errors_3f then
    local function _180_(_179_)
      local fnl_abs = _179_["fnl-abs"]
      local lua_abs = _179_["lua-abs"]
      local error = _179_.error
      return {string.format("\226\152\146  %s\n%s\n", fnl_abs, error), "DiagnosticError"}
    end
    extend_report(compile_errors, _180_)
    local function _181_()
      if atomic_3f then
        return {"`atomic? = true`, no changes were written to disk!\n", "DiagnosticWarn"}
      else
        return nil
      end
    end
    local function _182_(_241)
      return _241
    end
    extend_report({{"\nSome files had compilation errors! ", "DiagnosticWarn"}, _181_()}, _182_)
  else
  end
  if (0 < #printable_report) then
    local function _184_()
      return vim.api.nvim_echo(printable_report, true, {})
    end
    vim.schedule(_184_)
  else
  end
  return data_report
end
return M