-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local fennel
do
  local case_1_, case_2_ = pcall(require, "hotpot.fennel-update.fennel")
  if ((case_1_ == true) and (nil ~= case_2_)) then
    local fennel0 = case_2_
    fennel = fennel0
  elseif (case_1_ == false) then
    fennel = require("hotpot.vendor.fennel")
  else
    fennel = nil
  end
end
local path = fennel.path
local macro_path = fennel["macro-path"]
fennel.path = table.concat({"./fnl/?.fnl", "./fnl/?/init.fnl", fennel.path}, ";")
fennel["macro-path"] = table.concat({"./fnl/?.fnlm", "./fnl/?/init.fnlm", "./fnl/?.fnl", "./fnl/?/init-macros.fnl", "./fnl/?/init.fnl", fennel["macro-path"]}, ";")
return fennel