-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("hotpot.util")
local R = _local_1_.R
local function context_report(root, ctx, err)
  vim.health.start(string.format("%s Context", root))
  if (nil ~= ctx) then
    local ctx0 = ctx
    vim.health.info(string.format("Target: {%s}", ctx0.target))
    vim.health.info(string.format("Source: `%s`", ctx0.path.source))
    return vim.health.info(string.format("Destination: `%s`", ctx0.path.dest))
  else
    local _ = ctx
    return vim.health.error(err)
  end
end
local function fennel_update_report()
  vim.health.start(":Hotpot fennel update")
  do
    local case_3_ = vim.fn.executable("curl")
    if (case_3_ == 1) then
      vim.health.ok("`curl` is executable")
    elseif (case_3_ == 0) then
      vim.health.warn("`curl` is not executable", "Install curl to run `:Hotpot fennel update`")
    else
    end
  end
  do
    local case_5_ = vim.uv.fs_stat(R.const.HOTPOT_FENNEL_UPDATE_ROOT)
    if (case_5_ == nil) then
      vim.health.error(string.format("Target directory missing: `%s`", R.const.HOTPOT_FENNEL_UPDATE_ROOT), "Should be automatically created on load, check parent directory permissions?")
    elseif (_G.type(case_5_) == "table") then
      vim.health.ok(string.format("Target directory exists: `%s`", R.const.HOTPOT_FENNEL_UPDATE_ROOT))
    else
    end
  end
  local lua_mod = vim.fs.joinpath(R.const.HOTPOT_FENNEL_UPDATE_LUA_ROOT, "fennel.lua")
  if vim.uv.fs_stat(lua_mod) then
    vim.health.ok(string.format("Downloaded lua module exists: `%s`", lua_mod))
    local case_7_, case_8_ = pcall(require, "hotpot.fennel-update.fennel")
    if ((case_7_ == true) and (nil ~= case_8_)) then
      local mod = case_8_
      return vim.health.ok(string.format("Using custom Fennel version: `%s`", mod.version))
    elseif ((case_7_ == false) and (nil ~= case_8_)) then
      local err = case_8_
      return vim.health.error("Downloaded fennel could not be loaded.", err)
    else
      return nil
    end
  else
    return vim.health.info(string.format("Using default Fennel version: `%s`", R.fennel.version))
  end
end
local function runtime_report()
  vim.health.start("Runtime Configuration")
  local errors = R.runtime.errors()
  local case_11_ = #errors
  if (case_11_ == 0) then
    return vim.health.ok("No errors")
  else
    local _ = case_11_
    for _0, e in ipairs(errors) do
      vim.health.error(e)
    end
    return nil
  end
end
local function first_use_config_sync_report()
  local path = R.const.HOTPOT_CONFIG_CACHE_FIRST_BOOT_OK
  local config_path = vim.fn.stdpath("config")
  vim.health.start(string.format("Initial %s Sync", config_path))
  vim.health.info(string.format("Marker path: `%s`", path))
  local case_13_ = vim.uv.fs_stat(path)
  if (case_13_ == nil) then
    return vim.health.error(string.format("Marker missing, Hotpot will attempt to sync `%s` next time Neovim is started.", config_path), ("Probably there were compilation errors when starting Neovim. " .. string.format("Try running `:Hotpot sync context=%s` to see any compiler errors.", config_path)))
  else
    local _ = case_13_
    return vim.health.ok(string.format("Marker exists, `%s` will only automatically sync on file save", config_path))
  end
end
local function check()
  do
    local config = vim.fn.stdpath("config")
    local ctx = R.context.new(config)
    local nearest = R.context.nearest(vim.uv.cwd())
    runtime_report()
    context_report(config, ctx)
    first_use_config_sync_report()
    if (nearest and (config ~= nearest)) then
      local case_15_, case_16_ = pcall(R.context.new, nearest)
      if ((case_15_ == true) and (nil ~= case_16_)) then
        local ctx0 = case_16_
        context_report(nearest, ctx0)
      elseif ((case_15_ == nil) and (nil ~= case_16_)) then
        local err = case_16_
        context_report(nearest, nil, err)
      else
      end
    else
    end
  end
  return fennel_update_report()
end
return {check = check}