-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local R = require("hotpot.util")
local M, m = {}, {}
local capabilities = {}
m.initialize = function(_params, callback)
  return callback(nil, {capabilities = capabilities})
end
m.shutdown = function(_params, callback)
  return callback(nil, nil)
end
m.cmd = function(dispatchers)
  if (nil == dispatchers) then
    _G.error("Missing argument dispatchers on fnl/hotpot/lsp.fnl:12", 2)
  else
  end
  local res = {}
  local meta = {dispatchers = dispatchers, ["request-id"] = 0, ["closing?"] = false}
  res.request = function(method, params, callback)
    do
      local case_2_ = m[method]
      if (nil ~= case_2_) then
        local func = case_2_
        func(params, callback)
      else
      end
    end
    meta["request-id"] = (meta["request-id"] + 1)
    return true, meta["request-id"]
  end
  res.notify = function(method, params)
    if (method == "exit") then
      return dispatchers.on_exit(0, 15)
    else
      return nil
    end
  end
  res.is_closing = function()
    return meta["closing?"]
  end
  res.terminate = function()
    meta["closing?"] = true
    return nil
  end
  return res
end
M["start-lsp"] = function(_5_)
  local root = _5_.root
  if (nil == root) then
    _G.error("Missing argument root on fnl/hotpot/lsp.fnl:37", 2)
  else
  end
  local home_path = vim.fs.normalize("~")
  local name_path
  do
    local case_7_ = vim.fs.relpath(home_path, root)
    if (case_7_ == nil) then
      name_path = root
    elseif (nil ~= case_7_) then
      local ctx_rel = case_7_
      name_path = ("~/" .. ctx_rel)
    else
      name_path = nil
    end
  end
  local client_id = vim.lsp.start({cmd = m.cmd, name = string.format("hotpot@%s", name_path), root_dir = root}, {attach = false})
  return client_id
end
local report_id = 0
M["emit-report"] = function(client_id, report)
  if (nil == report) then
    _G.error("Missing argument report on fnl/hotpot/lsp.fnl:80", 2)
  else
  end
  if (nil == client_id) then
    _G.error("Missing argument client-id on fnl/hotpot/lsp.fnl:80", 2)
  else
  end
  local client = vim.lsp.get_client_by_id(client_id)
  local handler = (client.handlers["$/progress"] or vim.lsp.handlers["$/progress"])
  local ctx_token_id = client.config.root_dir
  local lsp_ctx = {method = "$/progress", client_id = client_id}
  report_id = (1 + report_id)
  local function send_progress(_11_)
    local token = _11_.token
    local title = _11_.title
    local message = _11_.message
    if (nil == message) then
      _G.error("Missing argument message on fnl/hotpot/lsp.fnl:87", 2)
    else
    end
    if (nil == title) then
      _G.error("Missing argument title on fnl/hotpot/lsp.fnl:87", 2)
    else
    end
    if (nil == token) then
      _G.error("Missing argument token on fnl/hotpot/lsp.fnl:87", 2)
    else
    end
    handler(nil, {token = token, value = {kind = "begin", title = title, message = message}}, lsp_ctx)
    return handler(nil, {token = token, value = {kind = "end", message = message}}, lsp_ctx)
  end
  for _, event in ipairs(report) do
    send_progress(event)
  end
  return nil
end
return M