-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("hotpot.util")
local R = _local_1_.R
local notify_info = _local_1_["notify-info"]
local notify_error = _local_1_["notify-error"]
local M = {}
local function default_sync_report_handler(ctx, report, invocation_meta)
  if (nil == invocation_meta) then
    _G.error("Missing argument invocation-meta on fnl/hotpot/runtime.fnl:4", 2)
  else
  end
  if (nil == report) then
    _G.error("Missing argument report on fnl/hotpot/runtime.fnl:4", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/runtime.fnl:4", 2)
  else
  end
  local verbose_3f = report["verbose?"]
  local atomic_3f = report["atomic?"]
  local root = ctx.locate("source")
  local total_duration_ms
  do
    local sum = 0
    for _, _5_ in ipairs(report.compiled) do
      local duration_ms = _5_["duration-ms"]
      sum = (sum + duration_ms)
    end
    total_duration_ms = sum
  end
  local nvim_echo_report = {}
  if verbose_3f then
    do
      local tbl_24_ = nvim_echo_report
      for _, _6_ in ipairs(report.compiled) do
        local fnl_abs = _6_["fnl-abs"]
        local lua_abs = _6_["lua-abs"]
        local duration_ms = _6_["duration-ms"]
        local val_25_ = {string.format("\226\152\145  %s (%.2fms)\n-> %s\n", fnl_abs, duration_ms, lua_abs), "DiagnosticOk"}
        table.insert(tbl_24_, val_25_)
      end
    end
    do
      local tbl_24_ = nvim_echo_report
      for _, _7_ in ipairs(report.cleaned.unowned) do
        local lua_abs = _7_["lua-abs"]
        local val_25_ = {string.format("rm %s\n", lua_abs), "DiagnosticInfo"}
        table.insert(tbl_24_, val_25_)
      end
    end
    table.insert(nvim_echo_report, {string.format("Duration %.2fms\n", total_duration_ms), "DiagnosticInfo"})
  else
  end
  do
    do
      local tbl_24_ = nvim_echo_report
      for _, _9_ in ipairs(report.errors) do
        local fnl_abs = _9_["fnl-abs"]
        local error = _9_.error
        local val_25_ = {string.format("\226\152\146  %s\n%s\n", fnl_abs, error), "DiagnosticError"}
        table.insert(tbl_24_, val_25_)
      end
    end
    if (0 < #report.errors) then
      if atomic_3f then
        table.insert(nvim_echo_report, {("Some files had compilation errors! " .. "`atomic? = true`, no changes were written to disk!\n"), "DiagnosticWarn"})
        table.insert(nvim_echo_report, {"Some files had compilation errors!\n", "DiagnosticWarn"})
      else
      end
    else
    end
  end
  if ((_G.type(invocation_meta) == "table") and (invocation_meta.reason == "command")) then
    if ((_G.type(report) == "table") and ((_G.type(report.errors) == "table") and (report.errors[1] == nil))) then
      table.insert(nvim_echo_report, {string.format("Synced %s", root), "DiagnosticInfo"})
    else
    end
  else
  end
  if (0 < #nvim_echo_report) then
    local function _14_()
      return vim.api.nvim_echo(nvim_echo_report, true, {})
    end
    vim.schedule(_14_)
  else
  end
  if not verbose_3f then
    local lsp_report = {}
    do
      do
        local tbl_24_ = lsp_report
        for i, _16_ in ipairs(report.compiled) do
          local fnl_rel = _16_["fnl-rel"]
          local duration_ms = _16_["duration-ms"]
          local val_25_ = {token = ("hotpot-sync-compiled-" .. root .. "-" .. i), title = "Compile", message = string.format("%s (%.2fms)", fnl_rel, duration_ms)}
          table.insert(tbl_24_, val_25_)
        end
      end
      if (1 < #report.compiled) then
        table.insert(lsp_report, {token = ("hotpot-sync-compiled-" .. root .. "-sum"), title = "Compile", message = string.format("Compiled %d files (%.2fms)", #report.compiled, total_duration_ms)})
      else
      end
    end
    do
      do
        local tbl_24_ = lsp_report
        for i, _18_ in ipairs(report.errors) do
          local fnl_rel = _18_["fnl-rel"]
          local val_25_ = {token = ("hotpot-sync-errors-" .. root .. "-" .. i), title = "Error", message = fnl_rel}
          table.insert(tbl_24_, val_25_)
        end
      end
      if (1 < #report.errors) then
        table.insert(lsp_report, {token = ("hotpot-sync-errors-" .. root .. "-sum"), title = "Error", message = string.format("Error compiling %d files", #report.errors)})
      else
      end
    end
    do
      do
        local tbl_24_ = lsp_report
        for i, _20_ in ipairs(report.cleaned.unowned) do
          local lua_rel = _20_["lua-rel"]
          local val_25_ = {token = ("hotpot-sync-cleaned-" .. root .. "-" .. i), title = "Clean", message = lua_rel}
          table.insert(tbl_24_, val_25_)
        end
      end
      if (1 < #report.cleaned.unowned) then
        table.insert(lsp_report, {token = ("hotpot-sync-cleaned-" .. root .. "-sum"), title = "Clean", message = string.format("Cleaned %d files", #report.cleaned.unowned)})
      else
      end
    end
    if ((_G.type(invocation_meta) == "table") and (invocation_meta.reason == "api")) then
      return nil
    else
      local _ = invocation_meta
      local client_id = R.lsp["start-lsp"]({root = root})
      return R.lsp["emit-report"](client_id, lsp_report)
    end
  else
    return nil
  end
end
local function make_default_config()
  return {["sync-report-handler"] = default_sync_report_handler}
end
local valid_options
local function _24_(_241)
  local case_25_ = type(_241)
  if (case_25_ == "function") then
    return true
  else
    local _ = case_25_
    return false, "must be 'function'"
  end
end
valid_options = {["sync-report-handler"] = _24_}
local runtime_configuration = make_default_config()
local configuration_errors = {}
M.apply = function(options)
  if (nil == options) then
    _G.error("Missing argument options on fnl/hotpot/runtime.fnl:111", 2)
  else
  end
  local new_runtime_config = make_default_config()
  local conf_err
  local function _28_(_241)
    return table.insert(configuration_errors, _241)
  end
  conf_err = _28_
  configuration_errors = {}
  for key, val in pairs(options) do
    local case_29_ = valid_options[key]
    if (case_29_ == nil) then
      conf_err(string.format("Unknown config option %q", key))
    elseif (nil ~= case_29_) then
      local validator = case_29_
      local case_30_, case_31_ = validator(val)
      if (case_30_ == true) then
        new_runtime_config[key] = val
      elseif ((case_30_ == false) and (nil ~= case_31_)) then
        local err = case_31_
        conf_err(string.format("Invalid config option %q: %s", key, err))
      else
      end
    else
    end
  end
  runtime_configuration = new_runtime_config
  return (0 == #configuration_errors), table.concat(configuration_errors, "\n")
end
M.errors = function()
  return configuration_errors
end
M["invoke-sync-report-handler"] = function(context, report, invocation)
  if (nil == invocation) then
    _G.error("Missing argument invocation on fnl/hotpot/runtime.fnl:128", 2)
  else
  end
  if (nil == report) then
    _G.error("Missing argument report on fnl/hotpot/runtime.fnl:128", 2)
  else
  end
  if (nil == context) then
    _G.error("Missing argument context on fnl/hotpot/runtime.fnl:128", 2)
  else
  end
  local function _37_(t, k)
    if (k == "source") then
      vim.notify_once(("Hotpot sync-report-handler: use `invocation-meta.reason`, " .. "`invocation-meta.source` is deprecated. " .. "This is to avoid confusion with the context `source`."), vim.log.levels.WARN)
      return t.reason
    else
      local _ = k
      return t[k]
    end
  end
  setmetatable(invocation, {__index = _37_})
  local case_39_ = runtime_configuration["sync-report-handler"]
  if (case_39_ == nil) then
    return notify_error("error: no `sync-report-handler` in runtime configuration")
  elseif (nil ~= case_39_) then
    local func = case_39_
    local case_40_, case_41_ = pcall(func, R.api.context(context), report, invocation)
    if (case_40_ == true) then
      return true
    elseif ((case_40_ == false) and (nil ~= case_41_)) then
      local err = case_41_
      notify_error("error in sync-report-handler: %s", err)
      return false
    else
      return nil
    end
  else
    return nil
  end
end
return M