-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local _local_1_ = require("hotpot.util")
local R = _local_1_.R
local notify_error = _local_1_["notify-error"]
local M = {}
local function default_sync_report_handler(ctx, report, invocation_meta)
  if (nil == invocation_meta) then
    _G.error("Missing argument invocation-meta on fnl/hotpot/runtime.fnl:5", 2)
  else
  end
  if (nil == report) then
    _G.error("Missing argument report on fnl/hotpot/runtime.fnl:5", 2)
  else
  end
  if (nil == ctx) then
    _G.error("Missing argument ctx on fnl/hotpot/runtime.fnl:5", 2)
  else
  end
  if ((_G.type(invocation_meta) == "table") and (invocation_meta.source == "api")) then
  else
    local _ = invocation_meta
    local client_id = R.lsp["start-lsp"]({root = ctx.locate("source")})
    return R.lsp["emit-report"](client_id, report)
  end
end
local function make_default_config()
  return {["sync-report-handler"] = default_sync_report_handler}
end
local valid_options
local function _6_(_241)
  local case_7_ = type(_241)
  if (case_7_ == "function") then
    return true
  else
    local _ = case_7_
    return false, "must be 'function'"
  end
end
valid_options = {["sync-report-handler"] = _6_}
local runtime_configuration = make_default_config()
local configuration_errors = {}
M.apply = function(options)
  if (nil == options) then
    _G.error("Missing argument options on fnl/hotpot/runtime.fnl:22", 2)
  else
  end
  local new_runtime_config = make_default_config()
  local conf_err
  local function _10_(_241)
    return table.insert(configuration_errors, _241)
  end
  conf_err = _10_
  configuration_errors = {}
  for key, val in pairs(options) do
    local case_11_ = valid_options[key]
    if (case_11_ == nil) then
      conf_err(string.format("Unknown config option %q", key))
    elseif (nil ~= case_11_) then
      local validator = case_11_
      local case_12_, case_13_ = validator(val)
      if (case_12_ == true) then
        new_runtime_config[key] = val
      elseif ((case_12_ == false) and (nil ~= case_13_)) then
        local err = case_13_
        conf_err(string.format("Invald config option %q: %s", key, err))
      else
      end
    else
    end
  end
  runtime_configuration = new_runtime_config
  return (0 == #configuration_errors), table.concat(configuration_errors, "\n")
end
M.errors = function()
  return configuration_errors
end
M["invoke-sync-report-handler"] = function(context, report, invocation)
  local case_16_ = runtime_configuration["sync-report-handler"]
  if (case_16_ == nil) then
    return notify_error("error: no `sync-report-handler` in runtime configuration")
  elseif (nil ~= case_16_) then
    local func = case_16_
    local case_17_, case_18_ = pcall(func, R.api.context(context), report, invocation)
    if (case_17_ == true) then
      return true
    elseif ((case_17_ == false) and (nil ~= case_18_)) then
      local err = case_18_
      notify_error("error in sync-report-handler: %s", err)
      return false
    else
      return nil
    end
  else
    return nil
  end
end
return M